In [10]:
# https://www.analyticsvidhya.com/blog/2021/04/how-to-download-kaggle-datasets-using-jupyter-notebook/

import opendatasets as od

od.download("https://www.kaggle.com/datasets/stefanoleone992/tripadvisor-european-restaurants")

# alexandertropin
# ea2bd9c043a1b0dbea99e82a6c45224f

Please provide your Kaggle credentials to download this dataset. Learn more: http://bit.ly/kaggle-creds
Your Kaggle username: alexandertropin
Your Kaggle Key: ········
Downloading tripadvisor-european-restaurants.zip to ./tripadvisor-european-restaurants

100%|████████████████████████████████████████| 102M/102M [00:35<00:00, 2.99MB/s]

In [19]:
# https://www.geeksforgeeks.org/how-to-download-kaggle-datasets-into-jupyter-notebook/
    
import pandas as pd
 
# reading the CSV file
file =('tripadvisor-european-restaurants/tripadvisor_european_restaurants.csv')
rest_df = pd.read_csv(file)
 
# displaying the contents of the XLSX file
rest_df.head()

/var/folders/zh/mnvg84rj3_7413ycjzpn5y8r0000gp/T/ipykernel_87406/3405525546.py:7: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  rest_df = pd.read_csv(file)

,restaurant_link,restaurant_name,original_location,country,region,province,city,address,latitude,longitude,...,excellent,very_good,average,poor,terrible,food,service,value,atmosphere,keywords
0,g10001637-d10002227,Le 147,"[""Europe"", ""France"", ""Nouvelle-Aquitaine"", ""Ha...",France,Nouvelle-Aquitaine,Haute-Vienne,Saint-Jouvent,"10 Maison Neuve, 87510 Saint-Jouvent France",45.961674,1.169131,...,2.0,0.0,0.0,0.0,0.0,4.0,4.5,4.0,NaN,NaN
1,g10001637-d14975787,Le Saint Jouvent,"[""Europe"", ""France"", ""Nouvelle-Aquitaine"", ""Ha...",France,Nouvelle-Aquitaine,Haute-Vienne,Saint-Jouvent,"16 Place de l Eglise, 87510 Saint-Jouvent France",45.957040,1.205480,...,2.0,2.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
2,g10002858-d4586832,Au Bout du Pont,"[""Europe"", ""France"", ""Centre-Val de Loire"", ""B...",France,Centre-Val de Loire,Berry,Rivarennes,"2 rue des Dames, 36800 Rivarennes France",46.635895,1.386133,...,3.0,1.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
3,g10002986-d3510044,Le Relais de Naiade,"[""Europe"", ""France"", ""Nouvelle-Aquitaine"", ""Co...",France,Nouvelle-Aquitaine,Correze,Lacelle,"9 avenue Porte de la Correze 19170, 19170 Lace...",45.642610,1.824460,...,1.0,0.0,0.0,0.0,0.0,4.5,4.5,4.5,NaN,NaN
4,g10022428-d9767191,Relais Du MontSeigne,"[""Europe"", ""France"", ""Occitanie"", ""Aveyron"", ""...",France,Occitanie,Aveyron,Saint-Laurent-de-Levezou,"route du Montseigne, 12620 Saint-Laurent-de-Le...",44.208860,2.960470,...,4.0,7.0,0.0,0.0,0.0,4.5,4.5,4.5,NaN,NaN

In [ ]:
# old but gold

# import pandas as pd

# df = pd.read_csv('tripadvisor_european_restaurants.csv')
# df.head()

In [20]:
rest_df.shape

(1083397, 42)

In [21]:
rest_df.isna().sum()

restaurant_link                           0
restaurant_name                           0
original_location                         0
country                                   0
region                                50323
province                             340632
city                                 400685
address                                   0
latitude                              15790
longitude                             15790
claimed                                1842
awards                               820264
popularity_detailed                   94988
popularity_generic                    97792
top_tags                             110634
price_level                          277205
price_range                          779070
meals                                448050
cuisines                             169103
special_diets                        743141
features                             765990
vegetarian_friendly                       0
vegan_options                             0
gluten_free                               0
original_open_hours                  489565
open_days_per_week                   489565
open_hours_per_week                  489565
working_shifts_per_week              489565
avg_rating                            96636
total_reviews_count                   52235
default_language                      95193
reviews_count_in_default_language     95193
excellent                             95193
very_good                             95193
average                               95193
poor                                  95193
terrible                              95193
food                                 484072
service                              479110
value                                480705
atmosphere                           821612
keywords                             984199
dtype: int64

In [23]:
rest_df.isna().sum() / df.shape[0] * 100.

restaurant_link                       0.000000
restaurant_name                       0.000000
original_location                     0.000000
country                               0.000000
region                                4.644927
province                             31.441106
city                                 36.984134
address                               0.000000
latitude                              1.457453
longitude                             1.457453
claimed                               0.170021
awards                               75.712227
popularity_detailed                   8.767608
popularity_generic                    9.026423
top_tags                             10.211769
price_level                          25.586650
price_range                          71.909928
meals                                41.356031
cuisines                             15.608590
special_diets                        68.593600
features                             70.702614
vegetarian_friendly                   0.000000
vegan_options                         0.000000
gluten_free                           0.000000
original_open_hours                  45.187960
open_days_per_week                   45.187960
open_hours_per_week                  45.187960
working_shifts_per_week              45.187960
avg_rating                            8.919722
total_reviews_count                   4.821409
default_language                      8.786530
reviews_count_in_default_language     8.786530
excellent                             8.786530
very_good                             8.786530
average                               8.786530
poor                                  8.786530
terrible                              8.786530
food                                 44.680943
service                              44.222940
value                                44.370162
atmosphere                           75.836651
keywords                             90.843800
dtype: float64

In [22]:
rest_df.dtypes

restaurant_link                       object
restaurant_name                       object
original_location                     object
country                               object
region                                object
province                              object
city                                  object
address                               object
latitude                             float64
longitude                            float64
claimed                               object
awards                                object
popularity_detailed                   object
popularity_generic                    object
top_tags                              object
price_level                           object
price_range                           object
meals                                 object
cuisines                              object
special_diets                         object
features                              object
vegetarian_friendly                   object
vegan_options                         object
gluten_free                           object
original_open_hours                   object
open_days_per_week                   float64
open_hours_per_week                  float64
working_shifts_per_week              float64
avg_rating                           float64
total_reviews_count                  float64
default_language                      object
reviews_count_in_default_language    float64
excellent                            float64
very_good                            float64
average                              float64
poor                                 float64
terrible                             float64
food                                 float64
service                              float64
value                                float64
atmosphere                           float64
keywords                              object
dtype: object