In [2]:
import pandas as pd

df = pd.read_csv('tripadvisor_european_restaurants.csv')
# df_prod = df.head(50)

/var/folders/zh/mnvg84rj3_7413ycjzpn5y8r0000gp/T/ipykernel_81067/2436082506.py:3: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('tripadvisor_european_restaurants.csv')

In [ ]:
'''

1. TO LOOK AT DATA

'''

In [3]:
df.shape

(1083397, 42)

In [4]:
df['top_tags_2'] = df['top_tags'].str.split(', ')
top_tags_list = list(set().union(*df['top_tags_2'].dropna()))

top_tags_list_2 = []
for top_tag in top_tags_list:
    top_tags_list_2.append([top_tag, df['top_tags_2'].dropna().map(set([top_tag]).issubset).fillna(False).value_counts()[True]])

top_tags_list_2 = sorted(top_tags_list_2, key=lambda x: x[1], reverse=True)
top_tags_list_2

[['Mid-range', 538207],
 ['Cheap Eats', 240351],
 ['Italian', 236822],
 ['European', 177712],
 ['Mediterranean', 155388],
 ['Vegetarian Friendly', 133520],
 ['Pizza', 113259],
 ['Cafe', 107793],
 ['French', 98892],
 ['Bar', 90677],
 ['Spanish', 82501],
 ['Seafood', 80241],
 ['British', 64133],
 ['Fast food', 58479],
 ['Pub', 53573],
 ['Asian', 45942],
 ['German', 36346],
 ['International', 32942],
 ['Quick Bites', 29544],
 ['Chinese', 29113],
 ['Dessert', 28969],
 ['Fine Dining', 28081],
 ['American', 27972],
 ['Greek', 26215],
 ['Indian', 21197],
 ['Japanese', 20717],
 ['Barbecue', 20511],
 ['Steakhouse', 18576],
 ['Portuguese', 17682],
 ['Vegan Options', 16240],
 ['Sushi', 15435],
 ['Healthy', 14077],
 ['Dutch', 14041],
 ['Bakeries', 13373],
 ['Grill', 13261],
 ['Belgian', 11558],
 ['Austrian', 11028],
 ['Central European', 11015],
 ['Turkish', 10264],
 ['Wine Bar', 9745],
 ['Contemporary', 9620],
 ['Thai', 9446],
 ['Polish', 9374],
 ['Brew Pub', 9062],
 ['Deli', 8498],
 ['Middle Eastern', 8494],
 ['Diner', 7613],
 ['Mexican', 7398],
 ['Gluten Free Options', 7357],
 ['Irish', 6496],
 ['Gastropub', 6396],
 ['Street Food', 5480],
 ['Fusion', 5447],
 ['Balti', 5155],
 ['Vietnamese', 5121],
 ['Czech', 4388],
 ['Northern-Italian', 4130],
 ['Swedish', 3598],
 ['Eastern European', 3560],
 ['Soups', 3261],
 ['Moroccan', 3199],
 ['Southern-Italian', 3190],
 ['Lebanese', 3091],
 ['South American', 3031],
 ['Latin', 3014],
 ['Scandinavian', 2864],
 ['Cantonese', 2791],
 ['Croatian', 2786],
 ['Central-Italian', 2487],
 ['Hungarian', 2305],
 ['Tuscan', 2249],
 ['African', 2191],
 ['Scottish', 2166],
 ['Brazilian', 2018],
 ['Dining bars', 1937],
 ['Danish', 1907],
 ['Caribbean', 1897],
 ['Neapolitan', 1836],
 ['Basque', 1697],
 ['Romanian', 1688],
 ['Emilian', 1635],
 ['Lombard', 1526],
 ['Sicilian', 1495],
 ['Argentinian', 1490],
 ['Romana', 1374],
 ['Korean', 1291],
 ['Speciality Food Market', 1184],
 ['Pakistani', 1133],
 ['Halal', 1050],
 ['Peruvian', 1026],
 ['Bangladeshi', 984],
 ['Catalan', 975],
 ['Arabic', 938],
 ['Campania', 773],
 ['Nepalese', 738],
 ['Hawaiian', 706],
 ['Ligurian', 674],
 ['Beer restaurants', 661],
 ['Indonesian', 650],
 ['Persian', 639],
 ['Central American', 613],
 ['Sardinian', 587],
 ['Welsh', 565],
 ['Lazio', 560],
 ['Venezuelan', 508],
 ['Russian', 503],
 ['Cajun & Creole', 495],
 ['Szechuan', 494],
 ['Hong Kong', 463],
 ['Japanese Fusion', 430],
 ['Swiss', 376],
 ['Israeli', 361],
 ['Jamaican', 340],
 ['Apulian', 336],
 ['Southwestern', 335],
 ['Afghani', 334],
 ['Ethiopian', 297],
 ['Cuban', 289],
 ['Taiwanese', 247],
 ['Tunisian', 247],
 ['Australian', 234],
 ['Sri Lankan', 228],
 ['Colombian', 223],
 ['Egyptian', 211],
 ['Philippine', 210],
 ['Central Asian', 204],
 ['Calabrian', 194],
 ['Malaysian', 183],
 ['Georgian', 174],
 ['Canadian', 169],
 ['Armenian', 165],
 ['Caucasian', 161],
 ['Mongolian', 151],
 ['Shanghai', 149],
 ['Albanian', 135],
 ['Delivery Only', 134],
 ['Cambodian', 118],
 ['Tibetan', 117],
 ['Fruit parlours', 116],
 ['Romagna', 110],
 ['Slovenian', 107],
 ['Kosher', 99],
 ['Algerian', 91],
 ['Ukrainian', 90],
 ['Chilean', 87],
 ['Dine With a Local Chef', 63],
 ['Native American', 58],
 ['Japanese sweets parlour', 57],
 ['Ecuadorean', 55],
 ['Medicinal foods', 53],
 ['Imperial Chinese', 40],
 ['Singaporean', 39],
 ['Beijing Specialties ', 36],
 ['Polynesian', 36],
 ['New Zealand', 34],
 ['Beijing cuisine', 31],
 ['Uzbek', 28],
 ['Azerbaijani', 25],
 ['NorthWestern Chinese', 25],
 ['Norwegian', 24],
 ['NorthEastern Chinese', 23],
 ['Hunan', 22],
 ['Nigerian', 21],
 ['Guatemalan', 20],
 ['Assyrian', 19],
 ['Salvadoran', 19],
 ['Bahamian', 16],
 ['Hokkaido cuisine', 15],
 ['Fujian', 14],
 ['Yunnan', 14],
 ['Anhui', 14],
 ['Xinjiang', 14],
 ['Burmese', 13],
 ['Zhejiang', 13],
 ['Latvian', 13],
 ['Kyoto cuisine', 12],
 ['Puerto Rican', 11],
 ['Costa Rican', 9],
 ['Kaiseki', 7],
 ['Nonya/Malaysian', 6],
 ['Kappo', 4],
 ['Shandong', 2],
 ['Guangxi', 2],
 ['Guizhou', 2],
 ['Hangzhou', 2],
 ['Jiangxi', 2],
 ['Kyushu cuisine', 2],
 ['Hubei', 1],
 ['Henan', 1]]

In [5]:
df['meals_2'] = df['meals'].str.split(', ')
list(set().union(*df['meals_2'].dropna()))

['After-hours', 'Dinner', 'Drinks', 'Lunch', 'Brunch', 'Breakfast']

In [6]:
df['cuisines'].value_counts()

Italian                                                          53243
French                                                           39103
Cafe                                                             35009
Spanish                                                          27339
Italian, Pizza                                                   26998
                                                                 ...
Italian, International, Mediterranean, Pizza, European               1
Italian, Bar, Pizza, Mediterranean, European, Gastropub              1
Italian, Mediterranean, Pizza, Wine Bar                              1
Grill, Fusion, Cafe, Spanish, Wine Bar                               1
French, American, Bar, International, European, Pub, Romanian        1
Name: cuisines, Length: 97741, dtype: int64

In [7]:
df['cuisines_2'] = df['cuisines'].str.split(', ')
cuisines_list = list(set().union(*df['cuisines_2'].dropna()))

cuisines_list_2 = []
for cuisine in cuisines_list:
    cuisines_list_2.append([cuisine, df['cuisines_2'].dropna().map(set([cuisine]).issubset).fillna(False).value_counts()[True]])

cuisines_list_2 = sorted(cuisines_list_2, key=lambda x: x[1], reverse=True)
cuisines_list_2

[['Italian', 235823],
 ['European', 208436],
 ['Mediterranean', 173020],
 ['Pizza', 114070],
 ['Cafe', 109188],
 ['French', 98480],
 ['Spanish', 93191],
 ['Bar', 90508],
 ['Pub', 82113],
 ['Seafood', 81397],
 ['British', 67673],
 ['Fast food', 61154],
 ['Asian', 53658],
 ['German', 36236],
 ['International', 34727],
 ['Greek', 30774],
 ['Chinese', 29046],
 ['American', 27921],
 ['Barbecue', 26997],
 ['Healthy', 26168],
 ['Portuguese', 23781],
 ['Grill', 22019],
 ['Indian', 21119],
 ['Japanese', 20645],
 ['Central European', 20349],
 ['Steakhouse', 18511],
 ['Southern-Italian', 18191],
 ['Sushi', 17777],
 ['Wine Bar', 17482],
 ['Gastropub', 14764],
 ['Contemporary', 14665],
 ['Dutch', 14076],
 ['Diner', 13444],
 ['Deli', 11621],
 ['Middle Eastern', 11588],
 ['Central-Italian', 11582],
 ['Belgian', 11549],
 ['Turkish', 11318],
 ['Austrian', 11026],
 ['Thai', 11004],
 ['Street Food', 10743],
 ['Fusion', 10702],
 ['Northern-Italian', 10249],
 ['Polish', 9367],
 ['Brew Pub', 9145],
 ['Soups', 7931],
 ['Mexican', 7364],
 ['Vietnamese', 7005],
 ['Campania', 6617],
 ['Neapolitan', 6397],
 ['Irish', 6338],
 ['South American', 6320],
 ['Croatian', 6279],
 ['Eastern European', 5974],
 ['Balti', 5763],
 ['Czech', 5716],
 ['Tuscan', 5666],
 ['Sicilian', 5666],
 ['Dining bars', 5058],
 ['Swedish', 4723],
 ['Scottish', 4692],
 ['Scandinavian', 4474],
 ['Hungarian', 3781],
 ['Lazio', 3771],
 ['Romana', 3653],
 ['Bangladeshi', 3504],
 ['Moroccan', 3225],
 ['Lebanese', 3078],
 ['Romanian', 3062],
 ['Latin', 3032],
 ['Catalan', 2999],
 ['Danish', 2973],
 ['Lombard', 2848],
 ['Emilian', 2535],
 ['Argentinian', 2509],
 ['Ligurian', 2356],
 ['Sardinian', 2252],
 ['Beer restaurants', 2201],
 ['African', 2197],
 ['Brazilian', 2040],
 ['Arabic', 1954],
 ['Pakistani', 1897],
 ['Caribbean', 1896],
 ['Korean', 1761],
 ['Central American', 1567],
 ['Welsh', 1372],
 ['Hawaiian', 1092],
 ['Japanese Fusion', 1086],
 ['Nepalese', 1052],
 ['Peruvian', 1015],
 ['Indonesian', 955],
 ['Persian', 836],
 ['Venezuelan', 762],
 ['Apulian', 714],
 ['Russian', 672],
 ['Tunisian', 661],
 ['Israeli', 611],
 ['Afghani', 588],
 ['Cajun & Creole', 507],
 ['Central Asian', 486],
 ['Cuban', 486],
 ['Jamaican', 469],
 ['Colombian', 466],
 ['Malaysian', 454],
 ['Mongolian', 440],
 ['Taiwanese', 434],
 ['Egyptian', 415],
 ['Swiss', 388],
 ['Australian', 384],
 ['Calabrian', 367],
 ['Southwestern', 361],
 ['Ethiopian', 352],
 ['Sri Lankan', 323],
 ['Caucasian', 318],
 ['Armenian', 313],
 ['Albanian', 285],
 ['Cambodian', 278],
 ['Canadian', 266],
 ['Georgian', 254],
 ['Fruit parlours', 240],
 ['Romagna', 229],
 ['Ukrainian', 224],
 ['Algerian', 218],
 ['Philippine', 212],
 ['Medicinal foods', 194],
 ['Slovenian', 177],
 ['Tibetan', 151],
 ['Chilean', 146],
 ['Singaporean', 120],
 ['Ecuadorean', 114],
 ['Native American', 105],
 ['Norwegian', 101],
 ['Japanese sweets parlour', 96],
 ['New Zealand', 69],
 ['Beijing cuisine', 66],
 ['Polynesian', 63],
 ['Azerbaijani', 56],
 ['Assyrian', 49],
 ['Fujian', 43],
 ['Uzbek', 42],
 ['Burmese', 36],
 ['Xinjiang', 35],
 ['Yunnan', 34],
 ['Puerto Rican', 33],
 ['Guatemalan', 32],
 ['Latvian', 32],
 ['Nigerian', 28],
 ['Bahamian', 28],
 ['Salvadoran', 26],
 ['Hokkaido cuisine', 25],
 ['Costa Rican', 25],
 ['Kyoto cuisine', 18],
 ['Kaiseki', 17],
 ['Kyushu cuisine', 8],
 ['Kappo', 6],
 ['Shojin', 2]]

In [8]:
df['features_2'] = df['features'].str.split(', ')
features_list = list(set().union(*df['features_2'].dropna()))

features_list_2 = []
for feature in features_list:
    features_list_2.append([feature, df['features_2'].dropna().map(set([feature]).issubset).fillna(False).value_counts()[True]])

features_list_2 = sorted(features_list_2, key=lambda x: x[1], reverse=True)
features_list_2

[['Seating', 228439],
 ['Reservations', 215387],
 ['Table Service', 191467],
 ['Wheelchair Accessible', 146385],
 ['Serves Alcohol', 129553],
 ['Takeout', 94983],
 ['Outdoor Seating', 74512],
 ['Accepts Credit Cards', 58121],
 ['Highchairs Available', 52849],
 ['Full Bar', 49332],
 ['Free Wifi', 41665],
 ['Parking Available', 27316],
 ['Wine and Beer', 25291],
 ['Delivery', 18758],
 ['Television', 17841],
 ['Accepts Visa', 17558],
 ['Accepts Mastercard', 16681],
 ['Street Parking', 14063],
 ['Free off-street parking', 12344],
 ['Digital Payments', 10863],
 ['Validated Parking', 7949],
 ['Accepts American Express', 7707],
 ['Gift Cards Available', 6103],
 ['Cash Only', 6046],
 ['Private Dining', 5075],
 ['Dog Friendly', 5064],
 ['Buffet', 4562],
 ['Family style', 4423],
 ['Live Music', 4080],
 ['Non-smoking restaurants', 2607],
 ['Waterfront', 1722],
 ['Accepts Discover', 1262],
 ['Valet Parking', 1155],
 ['Playgrounds', 1141],
 ['Beach', 668],
 ['Drive Thru', 499],
 ['BYOB', 494],
 ['Sports bars', 409],
 ['Jazz Bar', 350]]

In [411]:
# def check_price_range(price_range):
#     counter = 0
#     for a in price_range:
#         if a not in '0123456789-€':
#             counter += 1
#     return counter

# df_price_range['test'] = df_price_range.apply(lambda x: check_price_range(x['index']),axis=1)
# df_price_range[df_price_range['test'] > 0]

# Swiss franc (CHF) == 0,96 Евро

In [9]:
df['default_language'].value_counts()

English          689754
All languages    298450
Name: default_language, dtype: int64

In [10]:
df['working_shifts_per_week'].value_counts()

7.0     269200
6.0     120076
5.0      39570
12.0     37983
14.0     30482
11.0     22390
10.0     19618
13.0     11757
8.0      11331
9.0      10837
4.0       8239
3.0       6051
2.0       3417
1.0       2751
15.0       130
Name: working_shifts_per_week, dtype: int64

In [ ]:
'''

2. TO ADD NEW FLAGS

'''

In [11]:
df_upd = df.drop(['address', 
                  'original_location', 
                  'awards', 
                  'popularity_detailed', 
                  'popularity_generic', 
                  'top_tags', 
                  'special_diets', 
                  'keywords', 
                  'default_language', 
                  'reviews_count_in_default_language'
                 ], axis=1)
df_upd

,restaurant_link,restaurant_name,country,region,province,city,latitude,longitude,claimed,price_level,...,poor,terrible,food,service,value,atmosphere,top_tags_2,meals_2,cuisines_2,features_2
0,g10001637-d10002227,Le 147,France,Nouvelle-Aquitaine,Haute-Vienne,Saint-Jouvent,45.961674,1.169131,Claimed,€,...,0.0,0.0,4.0,4.5,4.0,NaN,"[Cheap Eats, French]","[Lunch, Dinner]",[French],"[Reservations, Seating, Wheelchair Accessible,..."
1,g10001637-d14975787,Le Saint Jouvent,France,Nouvelle-Aquitaine,Haute-Vienne,Saint-Jouvent,45.957040,1.205480,Unclaimed,€,...,0.0,0.0,NaN,NaN,NaN,NaN,[Cheap Eats],NaN,NaN,NaN
2,g10002858-d4586832,Au Bout du Pont,France,Centre-Val de Loire,Berry,Rivarennes,46.635895,1.386133,Claimed,€,...,0.0,0.0,NaN,NaN,NaN,NaN,"[Cheap Eats, French, European]","[Dinner, Lunch, Drinks]","[French, European]","[Reservations, Seating, Table Service, Wheelch..."
3,g10002986-d3510044,Le Relais de Naiade,France,Nouvelle-Aquitaine,Correze,Lacelle,45.642610,1.824460,Claimed,€,...,0.0,0.0,4.5,4.5,4.5,NaN,"[Cheap Eats, French]","[Lunch, Dinner]",[French],"[Reservations, Seating, Serves Alcohol, Table ..."
4,g10022428-d9767191,Relais Du MontSeigne,France,Occitanie,Aveyron,Saint-Laurent-de-Levezou,44.208860,2.960470,Unclaimed,€€-€€€,...,0.0,0.0,4.5,4.5,4.5,NaN,"[Mid-range, French]","[Lunch, Dinner]",[French],"[Reservations, Seating, Wheelchair Accessible,..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1083392,g9710275-d10770782,Complex Popas Pacurari,Romania,Northeast Romania,Iasi County,NaN,47.172950,27.519110,Unclaimed,NaN,...,0.0,1.0,NaN,NaN,NaN,NaN,NaN,"[Lunch, Dinner]",NaN,NaN
1083393,g9716321-d15026574,Casa Pastravarului DORIPESCO,Romania,Transylvania,Brasov County,Apata,45.904423,25.470509,Claimed,€€-€€€,...,1.0,2.0,NaN,NaN,NaN,NaN,"[Mid-range, Eastern European]","[Breakfast, Lunch, Dinner, Brunch, Drinks]",[Eastern European],NaN
1083394,g9722813-d15891057,Hanul Tentea,Romania,Transylvania,Maramures County,Sacel,47.631920,24.450910,Unclaimed,NaN,...,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1083395,g9726871-d21391722,Casa Paduraru,Romania,Southern Romania,Arges County,NaN,44.918950,24.867634,Claimed,€,...,NaN,NaN,NaN,NaN,NaN,NaN,"[Cheap Eats, French, American, Bar]","[Breakfast, Lunch, Dinner, Brunch, Drinks]","[French, American, Bar, International, Europea...",NaN
1083396,g9867250-d14979687,Pastravaria Alina Sarbi,Romania,Transylvania,Maramures County,Budesti,47.752220,23.938343,Unclaimed,NaN,...,0.0,1.0,NaN,NaN,NaN,NaN,[Diner],NaN,[Diner],NaN

In [12]:
def theUK(country):
    if country in ['England', 'Scotland', 'Wales', 'Northern Ireland']:
        return 'United Kingdom'
    else:
        return country
        
df_upd['country_origin'] = df_upd['country']
df_upd['country'] = df_upd.apply(lambda x: theUK(x['country']),axis=1)

# df_upd['country'].value_counts()

In [13]:
# flags of existence of meal options

df_upd['meals_2'] = df_upd['meals'].str.split(', ')

meals_list = list(set().union(*df_upd['meals_2'].dropna()))

meals_list_2 = []
for meal in meals_list:
    meals_list_2.append([meal, df_upd['meals_2'].dropna().map(set([meal]).issubset).fillna(False).value_counts()[True]])
meals_list_3 = [m[0] for m in meals_list_2]
# meals_list_3

meals_flg_list = []
for f in meals_list_3:
    name = 'meals_'+str.lower(f).replace(" ", "_")+'_flg'
    name = name.replace("-", "_")
    meals_flg_list.append(name)
    df_upd[name] = df_upd['meals_2'].dropna().map(set([f]).issubset)
    df_upd[name] = df_upd[name].fillna(False)
    
df_upd = df_upd.drop(['meals_2'], axis=1)
df_upd

,restaurant_link,restaurant_name,country,region,province,city,latitude,longitude,claimed,price_level,...,top_tags_2,cuisines_2,features_2,country_origin,meals_after_hours_flg,meals_dinner_flg,meals_drinks_flg,meals_lunch_flg,meals_brunch_flg,meals_breakfast_flg
0,g10001637-d10002227,Le 147,France,Nouvelle-Aquitaine,Haute-Vienne,Saint-Jouvent,45.961674,1.169131,Claimed,€,...,"[Cheap Eats, French]",[French],"[Reservations, Seating, Wheelchair Accessible,...",France,False,True,False,True,False,False
1,g10001637-d14975787,Le Saint Jouvent,France,Nouvelle-Aquitaine,Haute-Vienne,Saint-Jouvent,45.957040,1.205480,Unclaimed,€,...,[Cheap Eats],NaN,NaN,France,False,False,False,False,False,False
2,g10002858-d4586832,Au Bout du Pont,France,Centre-Val de Loire,Berry,Rivarennes,46.635895,1.386133,Claimed,€,...,"[Cheap Eats, French, European]","[French, European]","[Reservations, Seating, Table Service, Wheelch...",France,False,True,True,True,False,False
3,g10002986-d3510044,Le Relais de Naiade,France,Nouvelle-Aquitaine,Correze,Lacelle,45.642610,1.824460,Claimed,€,...,"[Cheap Eats, French]",[French],"[Reservations, Seating, Serves Alcohol, Table ...",France,False,True,False,True,False,False
4,g10022428-d9767191,Relais Du MontSeigne,France,Occitanie,Aveyron,Saint-Laurent-de-Levezou,44.208860,2.960470,Unclaimed,€€-€€€,...,"[Mid-range, French]",[French],"[Reservations, Seating, Wheelchair Accessible,...",France,False,True,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1083392,g9710275-d10770782,Complex Popas Pacurari,Romania,Northeast Romania,Iasi County,NaN,47.172950,27.519110,Unclaimed,NaN,...,NaN,NaN,NaN,Romania,False,True,False,True,False,False
1083393,g9716321-d15026574,Casa Pastravarului DORIPESCO,Romania,Transylvania,Brasov County,Apata,45.904423,25.470509,Claimed,€€-€€€,...,"[Mid-range, Eastern European]",[Eastern European],NaN,Romania,False,True,True,True,True,True
1083394,g9722813-d15891057,Hanul Tentea,Romania,Transylvania,Maramures County,Sacel,47.631920,24.450910,Unclaimed,NaN,...,NaN,NaN,NaN,Romania,False,False,False,False,False,False
1083395,g9726871-d21391722,Casa Paduraru,Romania,Southern Romania,Arges County,NaN,44.918950,24.867634,Claimed,€,...,"[Cheap Eats, French, American, Bar]","[French, American, Bar, International, Europea...",NaN,Romania,False,True,True,True,True,True
1083396,g9867250-d14979687,Pastravaria Alina Sarbi,Romania,Transylvania,Maramures County,Budesti,47.752220,23.938343,Unclaimed,NaN,...,[Diner],[Diner],NaN,Romania,False,False,False,False,False,False

In [14]:
# flags of existence of feature options 

df_upd['features_2'] = df_upd['features'].str.split(', ')

features_list = list(set().union(*df_upd['features_2'].dropna()))

features_list_2 = []
for feature in features_list:
    features_list_2.append([feature, df_upd['features_2'].dropna().map(set([feature]).issubset).fillna(False).value_counts()[True]])

features_list_2 = sorted(features_list_2, key=lambda x: x[1], reverse=True)
features_list_top_11 = [f[0] for f in features_list_2[:11] ]

features_flg_list = []
for f in features_list_top_11:
    name = 'features_'+str.lower(f).replace(" ", "_")+'_flg'
    features_flg_list.append(name)
    df_upd[name] = df_upd['features_2'].dropna().map(set([f]).issubset)
    df_upd[name] = df_upd[name].fillna(False)

df_upd = df_upd.drop(['features_2'], axis=1)
df_upd

,restaurant_link,restaurant_name,country,region,province,city,latitude,longitude,claimed,price_level,...,features_reservations_flg,features_table_service_flg,features_wheelchair_accessible_flg,features_serves_alcohol_flg,features_takeout_flg,features_outdoor_seating_flg,features_accepts_credit_cards_flg,features_highchairs_available_flg,features_full_bar_flg,features_free_wifi_flg
0,g10001637-d10002227,Le 147,France,Nouvelle-Aquitaine,Haute-Vienne,Saint-Jouvent,45.961674,1.169131,Claimed,€,...,True,True,True,True,False,False,True,False,False,False
1,g10001637-d14975787,Le Saint Jouvent,France,Nouvelle-Aquitaine,Haute-Vienne,Saint-Jouvent,45.957040,1.205480,Unclaimed,€,...,False,False,False,False,False,False,False,False,False,False
2,g10002858-d4586832,Au Bout du Pont,France,Centre-Val de Loire,Berry,Rivarennes,46.635895,1.386133,Claimed,€,...,True,True,True,False,False,False,False,False,False,False
3,g10002986-d3510044,Le Relais de Naiade,France,Nouvelle-Aquitaine,Correze,Lacelle,45.642610,1.824460,Claimed,€,...,True,True,True,True,False,False,False,False,False,False
4,g10022428-d9767191,Relais Du MontSeigne,France,Occitanie,Aveyron,Saint-Laurent-de-Levezou,44.208860,2.960470,Unclaimed,€€-€€€,...,True,True,True,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1083392,g9710275-d10770782,Complex Popas Pacurari,Romania,Northeast Romania,Iasi County,NaN,47.172950,27.519110,Unclaimed,NaN,...,False,False,False,False,False,False,False,False,False,False
1083393,g9716321-d15026574,Casa Pastravarului DORIPESCO,Romania,Transylvania,Brasov County,Apata,45.904423,25.470509,Claimed,€€-€€€,...,False,False,False,False,False,False,False,False,False,False
1083394,g9722813-d15891057,Hanul Tentea,Romania,Transylvania,Maramures County,Sacel,47.631920,24.450910,Unclaimed,NaN,...,False,False,False,False,False,False,False,False,False,False
1083395,g9726871-d21391722,Casa Paduraru,Romania,Southern Romania,Arges County,NaN,44.918950,24.867634,Claimed,€,...,False,False,False,False,False,False,False,False,False,False
1083396,g9867250-d14979687,Pastravaria Alina Sarbi,Romania,Transylvania,Maramures County,Budesti,47.752220,23.938343,Unclaimed,NaN,...,False,False,False,False,False,False,False,False,False,False

In [15]:
# to parse price_range in min and max values

def price_range_to_2_columns(price_range):
    price_range = price_range.replace(",", "")
    price_range = price_range.replace("€", "")
    price_range = price_range.replace("CHF ", "")
    price_range = price_range.replace("CHF\xa0", "")  # НЕРАЗРЫВНЫЙ ПРОБЕЛ
    price = price_range.split('-')
    
    price_min = int(price[0])
    price_max = int(price[1])

    return [price_min, price_max]

def correct_price_range(cell):
    price_range_dict = {}
    if cell is None:
        price_min, price_max = None, None
    else:
        price_min, price_max = price_range_to_2_columns(cell)
    price_range_dict['price_min'] = price_min
    price_range_dict['price_max'] = price_max
    return price_range_dict

# price_range = '€10-€30'
# price_range = 'CHF 6-CHF 17'
# correct_price_range(price_range)

In [16]:
df_price = df_upd[['restaurant_link','price_range']].dropna()
df_price2 = df_price['price_range'].apply(lambda x: pd.Series(correct_price_range(x)))
# df_price2
df_price4 = df_upd[['restaurant_link']].merge(
    df_price2,
    left_index=True, right_index=True
)
df_price4

df_upd = df_upd.join(df_price4.set_index('restaurant_link'), on='restaurant_link')
df_upd = df_upd.drop(['price_range'], axis=1)
df_upd

,restaurant_link,restaurant_name,country,region,province,city,latitude,longitude,claimed,price_level,...,features_wheelchair_accessible_flg,features_serves_alcohol_flg,features_takeout_flg,features_outdoor_seating_flg,features_accepts_credit_cards_flg,features_highchairs_available_flg,features_full_bar_flg,features_free_wifi_flg,price_min,price_max
0,g10001637-d10002227,Le 147,France,Nouvelle-Aquitaine,Haute-Vienne,Saint-Jouvent,45.961674,1.169131,Claimed,€,...,True,True,False,False,True,False,False,False,NaN,NaN
1,g10001637-d14975787,Le Saint Jouvent,France,Nouvelle-Aquitaine,Haute-Vienne,Saint-Jouvent,45.957040,1.205480,Unclaimed,€,...,False,False,False,False,False,False,False,False,NaN,NaN
2,g10002858-d4586832,Au Bout du Pont,France,Centre-Val de Loire,Berry,Rivarennes,46.635895,1.386133,Claimed,€,...,True,False,False,False,False,False,False,False,NaN,NaN
3,g10002986-d3510044,Le Relais de Naiade,France,Nouvelle-Aquitaine,Correze,Lacelle,45.642610,1.824460,Claimed,€,...,True,True,False,False,False,False,False,False,NaN,NaN
4,g10022428-d9767191,Relais Du MontSeigne,France,Occitanie,Aveyron,Saint-Laurent-de-Levezou,44.208860,2.960470,Unclaimed,€€-€€€,...,True,False,False,False,False,False,False,False,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1083392,g9710275-d10770782,Complex Popas Pacurari,Romania,Northeast Romania,Iasi County,NaN,47.172950,27.519110,Unclaimed,NaN,...,False,False,False,False,False,False,False,False,NaN,NaN
1083393,g9716321-d15026574,Casa Pastravarului DORIPESCO,Romania,Transylvania,Brasov County,Apata,45.904423,25.470509,Claimed,€€-€€€,...,False,False,False,False,False,False,False,False,NaN,NaN
1083394,g9722813-d15891057,Hanul Tentea,Romania,Transylvania,Maramures County,Sacel,47.631920,24.450910,Unclaimed,NaN,...,False,False,False,False,False,False,False,False,NaN,NaN
1083395,g9726871-d21391722,Casa Paduraru,Romania,Southern Romania,Arges County,NaN,44.918950,24.867634,Claimed,€,...,False,False,False,False,False,False,False,False,2.0,8.0
1083396,g9867250-d14979687,Pastravaria Alina Sarbi,Romania,Transylvania,Maramures County,Budesti,47.752220,23.938343,Unclaimed,NaN,...,False,False,False,False,False,False,False,False,NaN,NaN

In [17]:
# to convert original_open_hours to datetime fields

import json
from datetime import datetime
from datetime import timedelta
import statistics

def ifNone(val):
    if val is None:
        return timedelta(seconds=0)
    else:
        return val

def day_schedule_to_4_columns(day_list):
    t_list = []
    for tt in day_list:
        for t in tt.split('-'):
            t_list.append(datetime.strptime('01/01/22 '+t+':00', '%d/%m/%y %H:%M:%S'))
#     если закрывается за полночь, то сместить в следующие сутки:
    if t_list != [] and t_list[-1] < t_list[0]:
        one_day = timedelta(days=1)
        t_list[-1] += one_day
    return t_list

def dict_by_cell(test_cell):
    test_dict = {}
    for key in json.loads(test_cell).keys():
        open_dttm = None
        close_dttm = None
        start_break_dttm = None
        end_break_dttm = None
        t_list = day_schedule_to_4_columns(json.loads(test_cell)[key])

        if t_list != []:
            open_dttm = t_list[0]
            close_dttm = t_list[-1]
            if t_list[1] != t_list[-1]:
                start_break_dttm = t_list[1]
                end_break_dttm = t_list[2]
            else:
                start_break_dttm = None
                end_break_dttm = None

        test_dict[key] = {
            'weekend_flg': (False, True)[key in ['Sat', 'Sun']],
            'open_dttm': open_dttm,
            'close_dttm': close_dttm,
            'start_break_dttm': start_break_dttm,
            'end_break_dttm': end_break_dttm,
            'open_hours': (ifNone(close_dttm)-ifNone(open_dttm))-(ifNone(end_break_dttm)-ifNone(start_break_dttm)),
    #         (test_dict[key]['close_dttm']-test_dict[key]['open_dttm'])-(ifNone(test_dict[key]['end_break_dttm'])-ifNone(test_dict[key]['start_break_dttm']))
            'break_hours': (ifNone(end_break_dttm)-ifNone(start_break_dttm))
        }
    return test_dict
    
def new_schedule_parameters(test_dict):
    schedule_dict = {}
    empty_flg = (False, True)[sum([1 for key in test_dict.keys() if test_dict[key]['open_dttm'] is not None]) >= 1]
    
    if empty_flg == 1:
        min_open_dttm = min([test_dict[key]['open_dttm'] for key in test_dict.keys() if test_dict[key]['open_dttm'] is not None])
#         min_open_sec = (min_open_dttm - datetime.datetime(1970,1,1)).total_seconds()
        min_open_sec = min_open_dttm.timestamp()
        max_close_dttm = max([test_dict[key]['close_dttm'] for key in test_dict.keys() if test_dict[key]['close_dttm'] is not None])
        max_close_sec = max_close_dttm.timestamp()

        break_flg = (False, True)[sum([1 for key in test_dict.keys() if test_dict[key]['start_break_dttm'] is not None]) >= 1]
        if len([test_dict[key]['break_hours'] for key in test_dict.keys() if test_dict[key]['start_break_dttm'] is not None]) > 0:
            max_break_hours = max([test_dict[key]['break_hours'] for key in test_dict.keys() if test_dict[key]['start_break_dttm'] is not None])
        else:
            max_break_hours = timedelta(seconds=0)
        
        # statistics.median()
        if len([test_dict[key]['open_hours'] for key in test_dict.keys() if test_dict[key]['open_dttm'] is not None and test_dict[key]['weekend_flg'] is False]) > 0:
            max_no_weekend_hours = max([test_dict[key]['open_hours'] for key in test_dict.keys() if test_dict[key]['open_dttm'] is not None and test_dict[key]['weekend_flg'] is False])
        else:
            max_no_weekend_hours = timedelta(seconds=0)
        if len([test_dict[key]['open_hours'] for key in test_dict.keys() if test_dict[key]['open_dttm'] is not None and test_dict[key]['weekend_flg'] is True]) > 0:
            max_weekend_hours = max([test_dict[key]['open_hours'] for key in test_dict.keys() if test_dict[key]['open_dttm'] is not None and test_dict[key]['weekend_flg'] is True])
        else:
            max_weekend_hours = timedelta(seconds=0)
            
        schedule_dict['min_open_dttm'] = min_open_dttm
        schedule_dict['min_open_sec'] = min_open_sec
        schedule_dict['max_close_dttm'] = max_close_dttm
        schedule_dict['max_close_sec'] = max_close_sec
        schedule_dict['break_flg'] = break_flg
        schedule_dict['max_break_hours'] = max_break_hours
        schedule_dict['max_no_weekend_hours'] = max_no_weekend_hours
        schedule_dict['max_weekend_hours'] = max_weekend_hours

        for key in test_dict.keys():
            schedule_dict[str.lower('open_%s_hours' % key)] = test_dict[key]['open_hours']
    
    return schedule_dict

In [18]:
df_schedule = df_upd[['restaurant_link','original_open_hours', 'country']].dropna()
df_schedule2 = df_schedule['original_open_hours'].apply(lambda x: pd.Series(new_schedule_parameters(dict_by_cell(x))))
df_schedule2.head(5)

,min_open_dttm,min_open_sec,max_close_dttm,max_close_sec,break_flg,max_break_hours,max_no_weekend_hours,max_weekend_hours,open_mon_hours,open_tue_hours,open_wed_hours,open_thu_hours,open_fri_hours,open_sat_hours,open_sun_hours
5,2022-01-01 09:00:00,1.641013e+09,2022-01-01 22:00:00,1.641060e+09,True,0 days 04:30:00,0 days 08:30:00,0 days 08:30:00,0 days 05:30:00,0 days 08:00:00,0 days 08:00:00,0 days 08:00:00,0 days 08:30:00,0 days 08:30:00,0 days 07:00:00
6,2022-01-01 12:00:00,1.641024e+09,2022-01-01 22:00:00,1.641060e+09,True,0 days 04:00:00,0 days 06:00:00,0 days 06:00:00,0 days 00:00:00,0 days 00:00:00,0 days 06:00:00,0 days 06:00:00,0 days 06:00:00,0 days 06:00:00,0 days 06:00:00
7,2022-01-01 10:00:00,1.641017e+09,2022-01-01 14:00:00,1.641031e+09,False,0 days 00:00:00,0 days 04:00:00,0 days 04:00:00,0 days 00:00:00,0 days 04:00:00,0 days 04:00:00,0 days 04:00:00,0 days 04:00:00,0 days 04:00:00,0 days 04:00:00
8,2022-01-01 12:00:00,1.641024e+09,2022-01-01 21:00:00,1.641056e+09,True,0 days 05:00:00,0 days 04:00:00,0 days 04:00:00,0 days 00:00:00,0 days 00:00:00,0 days 02:00:00,0 days 02:00:00,0 days 04:00:00,0 days 02:00:00,0 days 04:00:00
9,2022-01-01 09:00:00,1.641013e+09,2022-01-01 23:45:00,1.641066e+09,False,0 days 00:00:00,0 days 12:00:00,0 days 08:00:00,0 days 00:00:00,0 days 07:00:00,0 days 07:00:00,0 days 12:00:00,0 days 12:00:00,0 days 07:00:00,0 days 08:00:00

In [19]:
df_schedule4 = df_upd[['restaurant_link', 'country']].merge(
    df_schedule2,
    left_index=True, right_index=True
)
df_schedule4.head(5)

,restaurant_link,country,min_open_dttm,min_open_sec,max_close_dttm,max_close_sec,break_flg,max_break_hours,max_no_weekend_hours,max_weekend_hours,open_mon_hours,open_tue_hours,open_wed_hours,open_thu_hours,open_fri_hours,open_sat_hours,open_sun_hours
5,g10029260-d6605477,France,2022-01-01 09:00:00,1.641013e+09,2022-01-01 22:00:00,1.641060e+09,True,0 days 04:30:00,0 days 08:30:00,0 days 08:30:00,0 days 05:30:00,0 days 08:00:00,0 days 08:00:00,0 days 08:00:00,0 days 08:30:00,0 days 08:30:00,0 days 07:00:00
6,g10029907-d17781655,France,2022-01-01 12:00:00,1.641024e+09,2022-01-01 22:00:00,1.641060e+09,True,0 days 04:00:00,0 days 06:00:00,0 days 06:00:00,0 days 00:00:00,0 days 00:00:00,0 days 06:00:00,0 days 06:00:00,0 days 06:00:00,0 days 06:00:00,0 days 06:00:00
7,g10029907-d8079764,France,2022-01-01 10:00:00,1.641017e+09,2022-01-01 14:00:00,1.641031e+09,False,0 days 00:00:00,0 days 04:00:00,0 days 04:00:00,0 days 00:00:00,0 days 04:00:00,0 days 04:00:00,0 days 04:00:00,0 days 04:00:00,0 days 04:00:00,0 days 04:00:00
8,g10036850-d8414223,France,2022-01-01 12:00:00,1.641024e+09,2022-01-01 21:00:00,1.641056e+09,True,0 days 05:00:00,0 days 04:00:00,0 days 04:00:00,0 days 00:00:00,0 days 00:00:00,0 days 02:00:00,0 days 02:00:00,0 days 04:00:00,0 days 02:00:00,0 days 04:00:00
9,g10054961-d3387712,France,2022-01-01 09:00:00,1.641013e+09,2022-01-01 23:45:00,1.641066e+09,False,0 days 00:00:00,0 days 12:00:00,0 days 08:00:00,0 days 00:00:00,0 days 07:00:00,0 days 07:00:00,0 days 12:00:00,0 days 12:00:00,0 days 07:00:00,0 days 08:00:00

In [20]:
# df_upd = df_upd.join(df_schedule4.set_index('restaurant_link'), on='restaurant_link')
df_upd = pd.merge(df_upd, df_schedule4,  how='left', left_on=['restaurant_link','country'], right_on = ['restaurant_link','country'])

# df_upd = df_upd.drop(['original_open_hours'], axis=1)
df_upd

,restaurant_link,restaurant_name,country,region,province,city,latitude,longitude,claimed,price_level,...,max_break_hours,max_no_weekend_hours,max_weekend_hours,open_mon_hours,open_tue_hours,open_wed_hours,open_thu_hours,open_fri_hours,open_sat_hours,open_sun_hours
0,g10001637-d10002227,Le 147,France,Nouvelle-Aquitaine,Haute-Vienne,Saint-Jouvent,45.961674,1.169131,Claimed,€,...,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT
1,g10001637-d14975787,Le Saint Jouvent,France,Nouvelle-Aquitaine,Haute-Vienne,Saint-Jouvent,45.957040,1.205480,Unclaimed,€,...,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT
2,g10002858-d4586832,Au Bout du Pont,France,Centre-Val de Loire,Berry,Rivarennes,46.635895,1.386133,Claimed,€,...,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT
3,g10002986-d3510044,Le Relais de Naiade,France,Nouvelle-Aquitaine,Correze,Lacelle,45.642610,1.824460,Claimed,€,...,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT
4,g10022428-d9767191,Relais Du MontSeigne,France,Occitanie,Aveyron,Saint-Laurent-de-Levezou,44.208860,2.960470,Unclaimed,€€-€€€,...,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1083392,g9710275-d10770782,Complex Popas Pacurari,Romania,Northeast Romania,Iasi County,NaN,47.172950,27.519110,Unclaimed,NaN,...,0 days,0 days 12:00:00,0 days 12:00:00,0 days 12:00:00,0 days 12:00:00,0 days 12:00:00,0 days 12:00:00,0 days 12:00:00,0 days 12:00:00,0 days 12:00:00
1083393,g9716321-d15026574,Casa Pastravarului DORIPESCO,Romania,Transylvania,Brasov County,Apata,45.904423,25.470509,Claimed,€€-€€€,...,0 days,0 days 14:00:00,0 days 14:00:00,0 days 14:00:00,0 days 14:00:00,0 days 14:00:00,0 days 14:00:00,0 days 14:00:00,0 days 14:00:00,0 days 14:00:00
1083394,g9722813-d15891057,Hanul Tentea,Romania,Transylvania,Maramures County,Sacel,47.631920,24.450910,Unclaimed,NaN,...,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT
1083395,g9726871-d21391722,Casa Paduraru,Romania,Southern Romania,Arges County,NaN,44.918950,24.867634,Claimed,€,...,0 days,0 days 11:00:00,0 days 00:00:00,0 days 11:00:00,0 days 11:00:00,0 days 11:00:00,0 days 11:00:00,0 days 11:00:00,0 days 00:00:00,0 days 00:00:00
1083396,g9867250-d14979687,Pastravaria Alina Sarbi,Romania,Transylvania,Maramures County,Budesti,47.752220,23.938343,Unclaimed,NaN,...,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT

In [21]:
ratio_parameters = ['vegetarian_friendly', 'vegan_options', 'gluten_free']

for r in ratio_parameters:
    df_upd[r].replace({"N": False, "Y": True}, inplace=True)

In [22]:
# df['cuisines'].value_counts()

df_upd['cuisines_2'] = df_upd['cuisines'].str.split(', ')
# cuisines_list = list(set().union(*df_upd['cuisines_2'].dropna()))

# cuisines_list_2 = []
# for cuisine in cuisines_list:
#     cuisines_list_2.append([cuisine, df['cuisines_2'].dropna().map(set([cuisine]).issubset).fillna(False).value_counts()[True]])

# cuisines_list_2 = sorted(cuisines_list_2, key=lambda x: x[1], reverse=True)
# cuisines_list_2

In [23]:
df_upd_short = df_upd
# list(df_upd_short)

In [20]:
# price anomalies

# df_upd_short[df_upd_short['price_max'] > 10000][['restaurant_name', 'price_min', 'price_max']].dropna().sort_values('price_max')

In [24]:
# df_upd_short.to_csv('tripadvisor_european_restaurants_upd_2.csv')

In [ ]:
'''

3. TO COLLECT DATASET WITH AGGREGATION BY COUNTRIES

'''

In [25]:
df_base = df_upd_short.groupby(['country'])['restaurant_name'].count().reset_index().rename(columns={"restaurant_name": "restaurant_cnt"})
df_base

            country  restaurant_cnt
0           Austria           20487
1           Belgium           23711
2          Bulgaria            4469
3           Croatia            8375
4    Czech Republic           14844
5           Denmark            9485
6           Finland            7372
7            France          155288
8           Germany          115333
9            Greece           33763
10          Hungary            7431
11          Ireland           11203
12            Italy          224763
13           Poland           24698
14         Portugal           32592
15          Romania            7842
16         Slovakia            4251
17            Spain          157479
18           Sweden           18555
19  The Netherlands           29792
20   United Kingdom          171664

In [26]:
country_cuisine_corr = {}

cuisines_list = list(set().union(*df_upd_short['cuisines_2'].dropna()))
for c in cuisines_list:
    country_cuisine_corr[c] = None

country_cuisine_corr['Italian'] = 'Italy'
country_cuisine_corr['French'] = 'France'
country_cuisine_corr['Spanish'] = 'Spain'
# country_cuisine_corr['British'] = 'England'
country_cuisine_corr['British'] = 'United Kingdom'
country_cuisine_corr['German'] = 'Germany'
country_cuisine_corr['Greek'] = 'Greece'
country_cuisine_corr['Portuguese'] = 'Portugal'
country_cuisine_corr['Southern-Italian'] = 'Italy'
country_cuisine_corr['Dutch'] = 'The Netherlands'
country_cuisine_corr['Central-Italian'] = 'Italy'
country_cuisine_corr['Belgian'] = 'Belgium'
country_cuisine_corr['Austrian'] = 'Austria'
country_cuisine_corr['Northern-Italian'] = 'Italy'
country_cuisine_corr['Polish'] = 'Poland'
country_cuisine_corr['Neapolitan'] = 'Italy'
country_cuisine_corr['Irish'] = 'Ireland'
country_cuisine_corr['Croatian'] = 'Croatia'
country_cuisine_corr['Sicilian'] = 'Italy'
country_cuisine_corr['Czech'] = 'Czech Republic'
country_cuisine_corr['Swedish'] = 'Sweden'
# country_cuisine_corr['Scottish'] = 'Scotland'
country_cuisine_corr['Scottish'] = 'United Kingdom'
country_cuisine_corr['Hungarian'] = 'Hungary'
country_cuisine_corr['Romanian'] = 'Romania'
country_cuisine_corr['Danish'] = 'Denmark'
# country_cuisine_corr['Welsh'] = 'Wales'
country_cuisine_corr['Welsh'] = 'United Kingdom'

# without own cuisine:
# Finland               7372
# Bulgaria              4469
# Slovakia              4251
# Northern Ireland      3634

country_cuisine_corr['Chinese'] = 'China'
country_cuisine_corr['American'] = 'USA'
country_cuisine_corr['Japanese'] = 'Japan'
country_cuisine_corr['Deli'] = 'India'
country_cuisine_corr['Turkish'] = 'Turkey'
country_cuisine_corr['Thai'] = 'Thailand'
country_cuisine_corr['Mexican'] = 'Mexico'
country_cuisine_corr['Vietnamese'] = 'Viet Nam'
# country_cuisine_corr['Tuscan'] = 'Italy'
# country_cuisine_corr['Romana'] = ''

from collections import Counter

# количество ресторанов с указанными кухнями
df_cuisines_2 = df_upd_short[['country','cuisines_2']].groupby(['country'])['cuisines_2'].count().reset_index().rename(columns={'cuisines_2':'cuisines_cnt'})
df_base = df_base.join(df_cuisines_2.set_index('country'), on='country')

# срез датасета с полями про кухню
df_cuisines = df_upd_short[['restaurant_link','country','cuisines_2']]  # 'cuisines',
# .sample(100000)

In [27]:
# довольно долго, минут 10

# создание ячеек с топ-3(?) названиями кухонь и количеством ресторанов с ними для каждой страны
df_cuisines_top = pd.DataFrame(df_cuisines.groupby('country')['cuisines_2'].sum()   # у каждой страны есть список названий с повторами
        .apply(lambda x: 
               [a[0] for a in Counter(x).most_common(3)] + 
               [a[1] for a in Counter(x).most_common(3)]
              ).tolist(),
#         columns=['cuisine_no_1','cuisine_no_2','cuisine_no_3','cuisine_no_1_cnt','cuisine_no_2_cnt','cuisine_no_3_cnt']
        columns =
                ['cuisine_no_'+str(i) for i in range(1,3+1)] +
                ['cuisine_no_'+str(i)+'_cnt' for i in range(1,3+1)]
     )

df_cuisines_top_ok = df_base.merge(
    df_cuisines_top,
    left_index=True, right_index=True
)
df_cuisines_top_ok

,country,restaurant_cnt,cuisines_cnt,cuisine_no_1,cuisine_no_2,cuisine_no_3,cuisine_no_1_cnt,cuisine_no_2_cnt,cuisine_no_3_cnt
0,Austria,20487,16760,European,Austrian,Central European,10582,9404,2743
1,Belgium,23711,20507,European,Belgian,French,11912,9992,4634
2,Bulgaria,4469,3851,European,Eastern European,Mediterranean,1589,980,664
3,Croatia,8375,7608,European,Croatian,Mediterranean,5348,5287,3529
4,Czech Republic,14844,11319,European,Czech,Cafe,6271,5394,1939
5,Denmark,9485,7117,European,Danish,Cafe,3186,2774,1288
6,Finland,7372,5802,European,Scandinavian,Cafe,2125,1204,1179
7,France,155288,132871,French,European,Italian,84643,31729,16140
8,Germany,115333,87491,German,European,Italian,32567,20365,15251
9,Greece,33763,30138,Greek,Mediterranean,Seafood,22191,13886,5541
10,Hungary,7431,6282,European,Hungarian,Central European,3732,3288,1109
11,Ireland,11203,9788,Irish,European,Cafe,4580,2863,2446
12,Italy,224763,195924,Italian,Mediterranean,Pizza,160924,58650,55432
13,Poland,24698,19033,European,Polish,Italian,10094,8865,3254
14,Portugal,32592,28680,European,Portuguese,Mediterranean,21440,21352,6867
15,Romania,7842,6865,European,Romanian,Italian,3766,2748,1484
16,Slovakia,4251,3147,European,Central European,Cafe,1368,630,599
17,Spain,157479,134965,Spanish,Mediterranean,European,85973,54333,23803
18,Sweden,18555,13384,European,Swedish,Cafe,5319,4400,2038
19,The Netherlands,29792,25588,European,Dutch,Seafood,15332,12410,4759
20,United Kingdom,171664,147174,British,Cafe,Bar,64264,34735,28771

In [28]:
df_base = df_base.join(df_cuisines_top_ok.drop(['restaurant_cnt','cuisines_cnt'], axis=1).set_index('country'), on='country')
# df_base

for i in range(1, 3+1):
    df_base['cuisine_no_'+str(i)+'_prt'] = df_base['cuisine_no_'+str(i)+'_cnt']/df_base['cuisines_cnt']
#     df_base = df_base.drop(['cuisine_no_'+str(i)+'_cnt'], axis=1)
    df_base['cuisine_no_'+str(i)+'_country'] = df_base['cuisine_no_'+str(i)].apply(lambda x: country_cuisine_corr[x])

df_base

,country,restaurant_cnt,cuisines_cnt,cuisine_no_1,cuisine_no_2,cuisine_no_3,cuisine_no_1_cnt,cuisine_no_2_cnt,cuisine_no_3_cnt,cuisine_no_1_prt,cuisine_no_1_country,cuisine_no_2_prt,cuisine_no_2_country,cuisine_no_3_prt,cuisine_no_3_country
0,Austria,20487,16760,European,Austrian,Central European,10582,9404,2743,0.631384,None,0.561098,Austria,0.163663,None
1,Belgium,23711,20507,European,Belgian,French,11912,9992,4634,0.580875,None,0.487248,Belgium,0.225972,France
2,Bulgaria,4469,3851,European,Eastern European,Mediterranean,1589,980,664,0.412620,None,0.254479,None,0.172423,None
3,Croatia,8375,7608,European,Croatian,Mediterranean,5348,5287,3529,0.702944,None,0.694926,Croatia,0.463854,None
4,Czech Republic,14844,11319,European,Czech,Cafe,6271,5394,1939,0.554024,None,0.476544,Czech Republic,0.171305,None
5,Denmark,9485,7117,European,Danish,Cafe,3186,2774,1288,0.447661,None,0.389771,Denmark,0.180975,None
6,Finland,7372,5802,European,Scandinavian,Cafe,2125,1204,1179,0.366253,None,0.207515,None,0.203206,None
7,France,155288,132871,French,European,Italian,84643,31729,16140,0.637031,France,0.238796,None,0.121471,Italy
8,Germany,115333,87491,German,European,Italian,32567,20365,15251,0.372233,Germany,0.232767,None,0.174315,Italy
9,Greece,33763,30138,Greek,Mediterranean,Seafood,22191,13886,5541,0.736313,Greece,0.460747,None,0.183854,None
10,Hungary,7431,6282,European,Hungarian,Central European,3732,3288,1109,0.594078,None,0.523400,Hungary,0.176536,None
11,Ireland,11203,9788,Irish,European,Cafe,4580,2863,2446,0.467920,Ireland,0.292501,None,0.249898,None
12,Italy,224763,195924,Italian,Mediterranean,Pizza,160924,58650,55432,0.821359,Italy,0.299351,None,0.282926,None
13,Poland,24698,19033,European,Polish,Italian,10094,8865,3254,0.530342,None,0.465770,Poland,0.170966,Italy
14,Portugal,32592,28680,European,Portuguese,Mediterranean,21440,21352,6867,0.747559,None,0.744491,Portugal,0.239435,None
15,Romania,7842,6865,European,Romanian,Italian,3766,2748,1484,0.548580,None,0.400291,Romania,0.216169,Italy
16,Slovakia,4251,3147,European,Central European,Cafe,1368,630,599,0.434700,None,0.200191,None,0.190340,None
17,Spain,157479,134965,Spanish,Mediterranean,European,85973,54333,23803,0.637002,Spain,0.402571,None,0.176364,None
18,Sweden,18555,13384,European,Swedish,Cafe,5319,4400,2038,0.397415,None,0.328751,Sweden,0.152271,None
19,The Netherlands,29792,25588,European,Dutch,Seafood,15332,12410,4759,0.599187,None,0.484993,The Netherlands,0.185986,None
20,United Kingdom,171664,147174,British,Cafe,Bar,64264,34735,28771,0.436653,United Kingdom,0.236013,None,0.195490,None

In [29]:
# ДОЛЯ НАЦИОНАЛЬНОЙ КУХНИ
# довольно долго, минут 10

df_base_test = df_upd_short.groupby(['country'])['restaurant_name'].count().reset_index().rename(columns={"restaurant_name": "restaurant_cnt"})
df_cuisines_test = df_cuisines[['country','cuisines_2']]
# .sample(10000)

# все кухни
df_all_cuisines = pd.DataFrame(df_cuisines_test.groupby('country')['cuisines_2'].sum()   # у каждой страны есть список названий с повторами
        .apply(lambda x: Counter(x)).tolist()
     )

df_all_cuisines_ok = df_base_test.merge(
    df_all_cuisines,
    left_index=True, right_index=True
)

cuisines_list = list(df_all_cuisines_ok.drop(['country', 'restaurant_cnt'], axis=1))

df_all_cuisines_ok2 = df_all_cuisines_ok.melt(id_vars = ['country', 'restaurant_cnt']).rename(columns={'variable': 'cuisine', 'value': 'cuisine_cnt'})
df_all_cuisines_ok2 = df_all_cuisines_ok2[df_all_cuisines_ok2['cuisine_cnt'] > 0].reset_index().drop(['index'],axis=1)

df_all_cuisines_ok3 = df_all_cuisines_ok2[df_all_cuisines_ok2['country'] == df_all_cuisines_ok2['cuisine'].apply(lambda x: country_cuisine_corr[x])]
# df_all_cuisines_ok3

# теперь надо просуммировать cuisine_cnt (из-за расщепления типа Italian)
df_all_cuisines_ok4 = df_all_cuisines_ok3.groupby('country').agg({
    'cuisine_cnt': 'sum', 
    'restaurant_cnt': 'mean'
}).reset_index().rename(columns={'cuisine_cnt':'national_cuisine_cnt'})
df_all_cuisines_ok4['national_cuisine_prt'] = df_all_cuisines_ok4['national_cuisine_cnt']/df_all_cuisines_ok4['restaurant_cnt']
df_all_cuisines_ok4

,country,national_cuisine_cnt,restaurant_cnt,national_cuisine_prt
0,Austria,9404.0,20487.0,0.459023
1,Belgium,9992.0,23711.0,0.421408
2,Croatia,5287.0,8375.0,0.631284
3,Czech Republic,5394.0,14844.0,0.363379
4,Denmark,2774.0,9485.0,0.292462
5,France,84643.0,155288.0,0.545071
6,Germany,32567.0,115333.0,0.282374
7,Greece,22191.0,33763.0,0.657258
8,Hungary,3288.0,7431.0,0.442471
9,Ireland,4580.0,11203.0,0.408819
10,Italy,205395.0,224763.0,0.913829
11,Poland,8865.0,24698.0,0.358936
12,Portugal,21352.0,32592.0,0.655130
13,Romania,2748.0,7842.0,0.350421
14,Spain,85973.0,157479.0,0.545933
15,Sweden,4400.0,18555.0,0.237133
16,The Netherlands,12410.0,29792.0,0.416555
17,United Kingdom,70193.0,171664.0,0.408898

In [31]:
df_all_cuisines_ok4 = df_all_cuisines_ok4.drop(columns=['restaurant_cnt'], axis=1)
df_base = df_base.join(df_all_cuisines_ok4.set_index('country'), on='country')
# df_base['national_cuisine_prt'].replace({"NaN": 0}, inplace=True)
df_base['national_cuisine_cnt'] = df_base['national_cuisine_cnt'].fillna(0)
df_base['national_cuisine_prt'] = df_base['national_cuisine_prt'].fillna(0)
df_base

,country,restaurant_cnt,cuisines_cnt,cuisine_no_1,cuisine_no_2,cuisine_no_3,cuisine_no_1_cnt,cuisine_no_2_cnt,cuisine_no_3_cnt,cuisine_no_1_prt,cuisine_no_1_country,cuisine_no_2_prt,cuisine_no_2_country,cuisine_no_3_prt,cuisine_no_3_country,national_cuisine_cnt,national_cuisine_prt
0,Austria,20487,16760,European,Austrian,Central European,10582,9404,2743,0.631384,None,0.561098,Austria,0.163663,None,9404.0,0.459023
1,Belgium,23711,20507,European,Belgian,French,11912,9992,4634,0.580875,None,0.487248,Belgium,0.225972,France,9992.0,0.421408
2,Bulgaria,4469,3851,European,Eastern European,Mediterranean,1589,980,664,0.412620,None,0.254479,None,0.172423,None,0.0,0.000000
3,Croatia,8375,7608,European,Croatian,Mediterranean,5348,5287,3529,0.702944,None,0.694926,Croatia,0.463854,None,5287.0,0.631284
4,Czech Republic,14844,11319,European,Czech,Cafe,6271,5394,1939,0.554024,None,0.476544,Czech Republic,0.171305,None,5394.0,0.363379
5,Denmark,9485,7117,European,Danish,Cafe,3186,2774,1288,0.447661,None,0.389771,Denmark,0.180975,None,2774.0,0.292462
6,Finland,7372,5802,European,Scandinavian,Cafe,2125,1204,1179,0.366253,None,0.207515,None,0.203206,None,0.0,0.000000
7,France,155288,132871,French,European,Italian,84643,31729,16140,0.637031,France,0.238796,None,0.121471,Italy,84643.0,0.545071
8,Germany,115333,87491,German,European,Italian,32567,20365,15251,0.372233,Germany,0.232767,None,0.174315,Italy,32567.0,0.282374
9,Greece,33763,30138,Greek,Mediterranean,Seafood,22191,13886,5541,0.736313,Greece,0.460747,None,0.183854,None,22191.0,0.657258
10,Hungary,7431,6282,European,Hungarian,Central European,3732,3288,1109,0.594078,None,0.523400,Hungary,0.176536,None,3288.0,0.442471
11,Ireland,11203,9788,Irish,European,Cafe,4580,2863,2446,0.467920,Ireland,0.292501,None,0.249898,None,4580.0,0.408819
12,Italy,224763,195924,Italian,Mediterranean,Pizza,160924,58650,55432,0.821359,Italy,0.299351,None,0.282926,None,205395.0,0.913829
13,Poland,24698,19033,European,Polish,Italian,10094,8865,3254,0.530342,None,0.465770,Poland,0.170966,Italy,8865.0,0.358936
14,Portugal,32592,28680,European,Portuguese,Mediterranean,21440,21352,6867,0.747559,None,0.744491,Portugal,0.239435,None,21352.0,0.655130
15,Romania,7842,6865,European,Romanian,Italian,3766,2748,1484,0.548580,None,0.400291,Romania,0.216169,Italy,2748.0,0.350421
16,Slovakia,4251,3147,European,Central European,Cafe,1368,630,599,0.434700,None,0.200191,None,0.190340,None,0.0,0.000000
17,Spain,157479,134965,Spanish,Mediterranean,European,85973,54333,23803,0.637002,Spain,0.402571,None,0.176364,None,85973.0,0.545933
18,Sweden,18555,13384,European,Swedish,Cafe,5319,4400,2038,0.397415,None,0.328751,Sweden,0.152271,None,4400.0,0.237133
19,The Netherlands,29792,25588,European,Dutch,Seafood,15332,12410,4759,0.599187,None,0.484993,The Netherlands,0.185986,None,12410.0,0.416555
20,United Kingdom,171664,147174,British,Cafe,Bar,64264,34735,28771,0.436653,United Kingdom,0.236013,None,0.195490,None,70193.0,0.408898

In [32]:
df_price_level = df_upd_short[['country','price_level']].groupby(['country']).value_counts().reset_index(name='counts')
# df_price_level
df_price_level_2 = df_price_level.pivot(index='country', columns='price_level', values='counts').reset_index()
# .rename(columns = {'€':'low', '€€-€€€':'middle', '€€€€':'high'}, inplace = True)
df_price_level_2['level_cnt'] = df_price_level_2['€']+df_price_level_2['€€-€€€']+df_price_level_2['€€€€']
df_price_level_2['level_low_part'] = df_price_level_2['€'] / df_price_level_2['level_cnt']
df_price_level_2['level_medium_part'] = df_price_level_2['€€-€€€'] / df_price_level_2['level_cnt']
df_price_level_2['level_high_part'] = df_price_level_2['€€€€'] / df_price_level_2['level_cnt']
# df_price_level_2

df_base = df_base.join(df_price_level_2.set_index('country'), on='country')
df_base

,country,restaurant_cnt,cuisines_cnt,cuisine_no_1,cuisine_no_2,cuisine_no_3,cuisine_no_1_cnt,cuisine_no_2_cnt,cuisine_no_3_cnt,cuisine_no_1_prt,...,cuisine_no_3_country,national_cuisine_cnt,national_cuisine_prt,€,€€-€€€,€€€€,level_cnt,level_low_part,level_medium_part,level_high_part
0,Austria,20487,16760,European,Austrian,Central European,10582,9404,2743,0.631384,...,None,9404.0,0.459023,2695,10267,621,13583,0.198410,0.755871,0.045719
1,Belgium,23711,20507,European,Belgian,French,11912,9992,4634,0.580875,...,France,9992.0,0.421408,3603,14198,935,18736,0.192304,0.757792,0.049904
2,Bulgaria,4469,3851,European,Eastern European,Mediterranean,1589,980,664,0.412620,...,None,0.0,0.000000,829,2176,108,3113,0.266303,0.699004,0.034693
3,Croatia,8375,7608,European,Croatian,Mediterranean,5348,5287,3529,0.702944,...,None,5287.0,0.631284,1415,4862,298,6575,0.215209,0.739468,0.045323
4,Czech Republic,14844,11319,European,Czech,Cafe,6271,5394,1939,0.554024,...,None,5394.0,0.363379,2930,6069,260,9259,0.316449,0.655470,0.028081
5,Denmark,9485,7117,European,Danish,Cafe,3186,2774,1288,0.447661,...,None,2774.0,0.292462,1391,4698,361,6450,0.215659,0.728372,0.055969
6,Finland,7372,5802,European,Scandinavian,Cafe,2125,1204,1179,0.366253,...,None,0.0,0.000000,941,3275,154,4370,0.215332,0.749428,0.035240
7,France,155288,132871,French,European,Italian,84643,31729,16140,0.637031,...,Italy,84643.0,0.545071,33063,86320,6100,125483,0.263486,0.687902,0.048612
8,Germany,115333,87491,German,European,Italian,32567,20365,15251,0.372233,...,Italy,32567.0,0.282374,18228,53939,2860,75027,0.242953,0.718928,0.038120
9,Greece,33763,30138,Greek,Mediterranean,Seafood,22191,13886,5541,0.736313,...,None,22191.0,0.657258,9613,16123,648,26384,0.364350,0.611090,0.024560
10,Hungary,7431,6282,European,Hungarian,Central European,3732,3288,1109,0.594078,...,None,3288.0,0.442471,1748,3501,169,5418,0.322628,0.646179,0.031192
11,Ireland,11203,9788,Irish,European,Cafe,4580,2863,2446,0.467920,...,None,4580.0,0.408819,2179,6184,188,8551,0.254824,0.723190,0.021986
12,Italy,224763,195924,Italian,Mediterranean,Pizza,160924,58650,55432,0.821359,...,None,205395.0,0.913829,60821,104754,6441,172016,0.353578,0.608978,0.037444
13,Poland,24698,19033,European,Polish,Italian,10094,8865,3254,0.530342,...,Italy,8865.0,0.358936,6710,8976,342,16028,0.418642,0.560020,0.021338
14,Portugal,32592,28680,European,Portuguese,Mediterranean,21440,21352,6867,0.747559,...,None,21352.0,0.655130,7956,16785,686,25427,0.312896,0.660125,0.026979
15,Romania,7842,6865,European,Romanian,Italian,3766,2748,1484,0.548580,...,Italy,2748.0,0.350421,1514,3433,213,5160,0.293411,0.665310,0.041279
16,Slovakia,4251,3147,European,Central European,Cafe,1368,630,599,0.434700,...,None,0.0,0.000000,809,1768,65,2642,0.306207,0.669190,0.024603
17,Spain,157479,134965,Spanish,Mediterranean,European,85973,54333,23803,0.637002,...,None,85973.0,0.545933,33489,79406,3913,116808,0.286701,0.679799,0.033499
18,Sweden,18555,13384,European,Swedish,Cafe,5319,4400,2038,0.397415,...,None,4400.0,0.237133,1814,8428,493,10735,0.168980,0.785095,0.045925
19,The Netherlands,29792,25588,European,Dutch,Seafood,15332,12410,4759,0.599187,...,None,12410.0,0.416555,4138,17497,722,22357,0.185087,0.782618,0.032294
20,United Kingdom,171664,147174,British,Cafe,Bar,64264,34735,28771,0.436653,...,None,70193.0,0.408898,44319,85259,2492,132070,0.335572,0.645559,0.018869

In [33]:
df_base2 = df_upd_short.groupby(['country'])[ratio_parameters].sum().reset_index()
# df_base2
df_base = df_base.join(df_base2.set_index('country'), on='country')
df_base['vegetarian_friendly_flg'] = df_base['vegetarian_friendly']/df_base['restaurant_cnt']
df_base['vegan_options_flg'] = df_base['vegan_options']/df_base['restaurant_cnt']
df_base['gluten_free_flg'] = df_base['gluten_free']/df_base['restaurant_cnt']
df_base

,country,restaurant_cnt,cuisines_cnt,cuisine_no_1,cuisine_no_2,cuisine_no_3,cuisine_no_1_cnt,cuisine_no_2_cnt,cuisine_no_3_cnt,cuisine_no_1_prt,...,level_cnt,level_low_part,level_medium_part,level_high_part,vegetarian_friendly,vegan_options,gluten_free,vegetarian_friendly_flg,vegan_options_flg,gluten_free_flg
0,Austria,20487,16760,European,Austrian,Central European,10582,9404,2743,0.631384,...,13583,0.198410,0.755871,0.045719,7385,1827,1279,0.360472,0.089179,0.062430
1,Belgium,23711,20507,European,Belgian,French,11912,9992,4634,0.580875,...,18736,0.192304,0.757792,0.049904,6143,1612,1228,0.259078,0.067985,0.051790
2,Bulgaria,4469,3851,European,Eastern European,Mediterranean,1589,980,664,0.412620,...,3113,0.266303,0.699004,0.034693,1043,531,276,0.233386,0.118819,0.061759
3,Croatia,8375,7608,European,Croatian,Mediterranean,5348,5287,3529,0.702944,...,6575,0.215209,0.739468,0.045323,3157,1171,1001,0.376955,0.139821,0.119522
4,Czech Republic,14844,11319,European,Czech,Cafe,6271,5394,1939,0.554024,...,9259,0.316449,0.655470,0.028081,2013,710,514,0.135610,0.047831,0.034627
5,Denmark,9485,7117,European,Danish,Cafe,3186,2774,1288,0.447661,...,6450,0.215659,0.728372,0.055969,1432,623,416,0.150975,0.065683,0.043859
6,Finland,7372,5802,European,Scandinavian,Cafe,2125,1204,1179,0.366253,...,4370,0.215332,0.749428,0.035240,1249,609,506,0.169425,0.082610,0.068638
7,France,155288,132871,French,European,Italian,84643,31729,16140,0.637031,...,125483,0.263486,0.687902,0.048612,26070,7622,2650,0.167882,0.049083,0.017065
8,Germany,115333,87491,German,European,Italian,32567,20365,15251,0.372233,...,75027,0.242953,0.718928,0.038120,41195,8986,4134,0.357183,0.077914,0.035844
9,Greece,33763,30138,Greek,Mediterranean,Seafood,22191,13886,5541,0.736313,...,26384,0.364350,0.611090,0.024560,11306,7767,4329,0.334864,0.230045,0.128217
10,Hungary,7431,6282,European,Hungarian,Central European,3732,3288,1109,0.594078,...,5418,0.322628,0.646179,0.031192,1823,810,582,0.245324,0.109003,0.078321
11,Ireland,11203,9788,Irish,European,Cafe,4580,2863,2446,0.467920,...,8551,0.254824,0.723190,0.021986,4711,2709,2779,0.420512,0.241810,0.248059
12,Italy,224763,195924,Italian,Mediterranean,Pizza,160924,58650,55432,0.821359,...,172016,0.353578,0.608978,0.037444,75289,27682,31140,0.334971,0.123161,0.138546
13,Poland,24698,19033,European,Polish,Italian,10094,8865,3254,0.530342,...,16028,0.418642,0.560020,0.021338,3443,1453,780,0.139404,0.058831,0.031582
14,Portugal,32592,28680,European,Portuguese,Mediterranean,21440,21352,6867,0.747559,...,25427,0.312896,0.660125,0.026979,6577,3311,3372,0.201798,0.101589,0.103461
15,Romania,7842,6865,European,Romanian,Italian,3766,2748,1484,0.548580,...,5160,0.293411,0.665310,0.041279,1357,685,312,0.173043,0.087350,0.039786
16,Slovakia,4251,3147,European,Central European,Cafe,1368,630,599,0.434700,...,2642,0.306207,0.669190,0.024603,508,188,131,0.119501,0.044225,0.030816
17,Spain,157479,134965,Spanish,Mediterranean,European,85973,54333,23803,0.637002,...,116808,0.286701,0.679799,0.033499,37739,19962,20654,0.239645,0.126760,0.131154
18,Sweden,18555,13384,European,Swedish,Cafe,5319,4400,2038,0.397415,...,10735,0.168980,0.785095,0.045925,3395,1555,1269,0.182970,0.083805,0.068391
19,The Netherlands,29792,25588,European,Dutch,Seafood,15332,12410,4759,0.599187,...,22357,0.185087,0.782618,0.032294,12271,3665,3431,0.411889,0.123020,0.115165
20,United Kingdom,171664,147174,British,Cafe,Bar,64264,34735,28771,0.436653,...,132070,0.335572,0.645559,0.018869,75911,43119,42714,0.442207,0.251183,0.248823

In [34]:
# meals_flg_list = ['meals_drinks_flg', 'meals_lunch_flg', 'meals_brunch_flg', 'meals_dinner_flg', 'meals_after_hours_flg', 'meals_breakfast_flg']
# meals_flg_list

df_base3 = df_upd_short.groupby(['country'])[meals_flg_list].sum().reset_index()
# df_base3
df_base = df_base.join(df_base3.set_index('country'), on='country')
for p in meals_flg_list:
    df_base[p] = df_base[p]/df_base['restaurant_cnt']
df_base

,country,restaurant_cnt,cuisines_cnt,cuisine_no_1,cuisine_no_2,cuisine_no_3,cuisine_no_1_cnt,cuisine_no_2_cnt,cuisine_no_3_cnt,cuisine_no_1_prt,...,gluten_free,vegetarian_friendly_flg,vegan_options_flg,gluten_free_flg,meals_after_hours_flg,meals_dinner_flg,meals_drinks_flg,meals_lunch_flg,meals_brunch_flg,meals_breakfast_flg
0,Austria,20487,16760,European,Austrian,Central European,10582,9404,2743,0.631384,...,1279,0.360472,0.089179,0.062430,0.046517,0.490409,0.094987,0.442183,0.064724,0.181383
1,Belgium,23711,20507,European,Belgian,French,11912,9992,4634,0.580875,...,1228,0.259078,0.067985,0.051790,0.057906,0.555017,0.077685,0.481169,0.068998,0.088103
2,Bulgaria,4469,3851,European,Eastern European,Mediterranean,1589,980,664,0.412620,...,276,0.233386,0.118819,0.061759,0.077646,0.471694,0.133363,0.462296,0.139852,0.219512
3,Croatia,8375,7608,European,Croatian,Mediterranean,5348,5287,3529,0.702944,...,1001,0.376955,0.139821,0.119522,0.112716,0.546866,0.119045,0.506985,0.120239,0.174806
4,Czech Republic,14844,11319,European,Czech,Cafe,6271,5394,1939,0.554024,...,514,0.135610,0.047831,0.034627,0.046888,0.464026,0.142549,0.468809,0.071072,0.149690
5,Denmark,9485,7117,European,Danish,Cafe,3186,2774,1288,0.447661,...,416,0.150975,0.065683,0.043859,0.033316,0.424038,0.113969,0.388719,0.086347,0.111228
6,Finland,7372,5802,European,Scandinavian,Cafe,2125,1204,1179,0.366253,...,506,0.169425,0.082610,0.068638,0.056294,0.370998,0.113673,0.422273,0.051682,0.143516
7,France,155288,132871,French,European,Italian,84643,31729,16140,0.637031,...,2650,0.167882,0.049083,0.017065,0.093130,0.576059,0.126043,0.596047,0.036107,0.121754
8,Germany,115333,87491,German,European,Italian,32567,20365,15251,0.372233,...,4134,0.357183,0.077914,0.035844,0.041497,0.516400,0.070422,0.435461,0.045104,0.123260
9,Greece,33763,30138,Greek,Mediterranean,Seafood,22191,13886,5541,0.736313,...,4329,0.334864,0.230045,0.128217,0.125848,0.442615,0.120635,0.431360,0.132453,0.200338
10,Hungary,7431,6282,European,Hungarian,Central European,3732,3288,1109,0.594078,...,582,0.245324,0.109003,0.078321,0.053290,0.426726,0.132015,0.445566,0.061903,0.164177
11,Ireland,11203,9788,Irish,European,Cafe,4580,2863,2446,0.467920,...,2779,0.420512,0.241810,0.248059,0.081585,0.431224,0.090511,0.468089,0.184861,0.243685
12,Italy,224763,195924,Italian,Mediterranean,Pizza,160924,58650,55432,0.821359,...,31140,0.334971,0.123161,0.138546,0.099696,0.463715,0.101907,0.405961,0.072819,0.149446
13,Poland,24698,19033,European,Polish,Italian,10094,8865,3254,0.530342,...,780,0.139404,0.058831,0.031582,0.102802,0.458742,0.164831,0.468297,0.102721,0.187788
14,Portugal,32592,28680,European,Portuguese,Mediterranean,21440,21352,6867,0.747559,...,3372,0.201798,0.101589,0.103461,0.080204,0.530928,0.116286,0.528719,0.077596,0.154639
15,Romania,7842,6865,European,Romanian,Italian,3766,2748,1484,0.548580,...,312,0.173043,0.087350,0.039786,0.075108,0.474751,0.139760,0.479725,0.143331,0.249426
16,Slovakia,4251,3147,European,Central European,Cafe,1368,630,599,0.434700,...,131,0.119501,0.044225,0.030816,0.054340,0.439896,0.153846,0.460127,0.078805,0.200659
17,Spain,157479,134965,Spanish,Mediterranean,European,85973,54333,23803,0.637002,...,20654,0.239645,0.126760,0.131154,0.098305,0.468577,0.118606,0.456899,0.103703,0.203087
18,Sweden,18555,13384,European,Swedish,Cafe,5319,4400,2038,0.397415,...,1269,0.182970,0.083805,0.068391,0.060523,0.347831,0.079601,0.359095,0.042684,0.090649
19,The Netherlands,29792,25588,European,Dutch,Seafood,15332,12410,4759,0.599187,...,3431,0.411889,0.123020,0.115165,0.034036,0.511849,0.105666,0.408163,0.159539,0.130438
20,United Kingdom,171664,147174,British,Cafe,Bar,64264,34735,28771,0.436653,...,42714,0.442207,0.251183,0.248823,0.089419,0.483037,0.107489,0.516719,0.187238,0.242602

In [35]:
# features_flg_list

df_base4 = df_upd_short.groupby(['country'])[features_flg_list].sum().reset_index()
# df_base4
df_base = df_base.join(df_base4.set_index('country'), on='country')
for p in features_flg_list:
    df_base[p] = df_base[p]/df_base['restaurant_cnt']
df_base

,country,restaurant_cnt,cuisines_cnt,cuisine_no_1,cuisine_no_2,cuisine_no_3,cuisine_no_1_cnt,cuisine_no_2_cnt,cuisine_no_3_cnt,cuisine_no_1_prt,...,features_reservations_flg,features_table_service_flg,features_wheelchair_accessible_flg,features_serves_alcohol_flg,features_takeout_flg,features_outdoor_seating_flg,features_accepts_credit_cards_flg,features_highchairs_available_flg,features_full_bar_flg,features_free_wifi_flg
0,Austria,20487,16760,European,Austrian,Central European,10582,9404,2743,0.631384,...,0.158296,0.107971,0.050129,0.045151,0.033387,0.032460,0.017621,0.020794,0.016254,0.020598
1,Belgium,23711,20507,European,Belgian,French,11912,9992,4634,0.580875,...,0.278689,0.243178,0.144026,0.152587,0.076420,0.067564,0.037156,0.036017,0.027034,0.024883
2,Bulgaria,4469,3851,European,Eastern European,Mediterranean,1589,980,664,0.412620,...,0.166704,0.139629,0.049899,0.086820,0.052137,0.075185,0.028418,0.026180,0.036026,0.049452
3,Croatia,8375,7608,European,Croatian,Mediterranean,5348,5287,3529,0.702944,...,0.226388,0.241433,0.104478,0.169433,0.062448,0.158925,0.052060,0.059343,0.066030,0.077134
4,Czech Republic,14844,11319,European,Czech,Cafe,6271,5394,1939,0.554024,...,0.144570,0.132175,0.063191,0.094988,0.060765,0.054972,0.045608,0.032808,0.049245,0.058273
5,Denmark,9485,7117,European,Danish,Cafe,3186,2774,1288,0.447661,...,0.135055,0.118187,0.073484,0.077174,0.086979,0.054823,0.059989,0.047338,0.023089,0.028571
6,Finland,7372,5802,European,Scandinavian,Cafe,2125,1204,1179,0.366253,...,0.074200,0.059821,0.064840,0.055887,0.053310,0.041373,0.042458,0.039745,0.025231,0.028893
7,France,155288,132871,French,European,Italian,84643,31729,16140,0.637031,...,0.316464,0.273537,0.198006,0.196776,0.099171,0.106396,0.086600,0.054724,0.040518,0.024451
8,Germany,115333,87491,German,European,Italian,32567,20365,15251,0.372233,...,0.154396,0.100006,0.044159,0.032853,0.034968,0.026029,0.009130,0.014731,0.008896,0.010249
9,Greece,33763,30138,Greek,Mediterranean,Seafood,22191,13886,5541,0.736313,...,0.132423,0.165270,0.096881,0.114534,0.083523,0.115067,0.072120,0.046738,0.049847,0.093890
10,Hungary,7431,6282,European,Hungarian,Central European,3732,3288,1109,0.594078,...,0.117750,0.111560,0.048580,0.080743,0.080474,0.059615,0.047907,0.034047,0.032566,0.061634
11,Ireland,11203,9788,Irish,European,Cafe,4580,2863,2446,0.467920,...,0.148621,0.151656,0.147818,0.120593,0.105686,0.051683,0.072748,0.094707,0.070338,0.077479
12,Italy,224763,195924,Italian,Mediterranean,Pizza,160924,58650,55432,0.821359,...,0.227168,0.192963,0.164289,0.120202,0.103126,0.060793,0.042556,0.040896,0.035727,0.024177
13,Poland,24698,19033,European,Polish,Italian,10094,8865,3254,0.530342,...,0.074662,0.083893,0.031824,0.049154,0.066240,0.038667,0.052474,0.020002,0.028909,0.037088
14,Portugal,32592,28680,European,Portuguese,Mediterranean,21440,21352,6867,0.747559,...,0.234689,0.264421,0.155376,0.188328,0.084131,0.087690,0.057928,0.078639,0.084745,0.077872
15,Romania,7842,6865,European,Romanian,Italian,3766,2748,1484,0.548580,...,0.164626,0.149962,0.053685,0.100867,0.074471,0.079572,0.047437,0.031115,0.045524,0.063122
16,Slovakia,4251,3147,European,Central European,Cafe,1368,630,599,0.434700,...,0.146083,0.122089,0.062338,0.083039,0.073159,0.072454,0.046342,0.043049,0.045872,0.072454
17,Spain,157479,134965,Spanish,Mediterranean,European,85973,54333,23803,0.637002,...,0.212930,0.228640,0.155748,0.149150,0.069533,0.076569,0.055182,0.034322,0.061684,0.037834
18,Sweden,18555,13384,European,Swedish,Cafe,5319,4400,2038,0.397415,...,0.093667,0.060415,0.063110,0.035354,0.059876,0.032821,0.045109,0.026516,0.024791,0.017030
19,The Netherlands,29792,25588,European,Dutch,Seafood,15332,12410,4759,0.599187,...,0.144569,0.103316,0.089689,0.060520,0.042058,0.041924,0.020274,0.023362,0.018629,0.026148
20,United Kingdom,171664,147174,British,Cafe,Bar,64264,34735,28771,0.436653,...,0.133511,0.112074,0.150125,0.110827,0.138701,0.070958,0.076900,0.101174,0.079749,0.071174

In [36]:
count_parameters = ['excellent', 'very_good', 'average', 'poor', 'terrible', 'total_reviews_count']
df_count = df_upd_short[['country'] + count_parameters].groupby(['country']).sum(count_parameters).reset_index()
df_count['corrrect_reviews_cnt'] = df_count['excellent']+df_count['very_good']+df_count['average']+df_count['poor']+df_count['terrible']
# df_count
df_base = df_base.join(df_count.set_index('country'), on='country')

df_base['excellent_flg'] = df_base['excellent']/df_base['corrrect_reviews_cnt']
df_base['excellent_and_very_good_flg'] = (df_base['excellent']+df_base['very_good'])/df_base['corrrect_reviews_cnt']
df_base['terrible_flg'] = df_base['terrible']/df_base['corrrect_reviews_cnt']
df_base['terrible_and_poor_flg'] = (df_base['terrible']+df_base['poor'])/df_base['corrrect_reviews_cnt']
df_base

,country,restaurant_cnt,cuisines_cnt,cuisine_no_1,cuisine_no_2,cuisine_no_3,cuisine_no_1_cnt,cuisine_no_2_cnt,cuisine_no_3_cnt,cuisine_no_1_prt,...,very_good,average,poor,terrible,total_reviews_count,corrrect_reviews_cnt,excellent_flg,excellent_and_very_good_flg,terrible_flg,terrible_and_poor_flg
0,Austria,20487,16760,European,Austrian,Central European,10582,9404,2743,0.631384,...,98463.0,33296.0,14849.0,18360.0,1030051.0,338928.0,0.513265,0.803778,0.054171,0.097982
1,Belgium,23711,20507,European,Belgian,French,11912,9992,4634,0.580875,...,135530.0,46453.0,23022.0,27968.0,1604926.0,436046.0,0.465715,0.776530,0.064140,0.116937
2,Bulgaria,4469,3851,European,Eastern European,Mediterranean,1589,980,664,0.412620,...,27467.0,11273.0,6110.0,8813.0,207750.0,140450.0,0.617921,0.813485,0.062748,0.106251
3,Croatia,8375,7608,European,Croatian,Mediterranean,5348,5287,3529,0.702944,...,100333.0,36748.0,19934.0,24701.0,922238.0,490173.0,0.629282,0.833971,0.050392,0.091060
4,Czech Republic,14844,11319,European,Czech,Cafe,6271,5394,1939,0.554024,...,92889.0,32900.0,16556.0,24819.0,883173.0,382738.0,0.563242,0.805938,0.064846,0.108103
5,Denmark,9485,7117,European,Danish,Cafe,3186,2774,1288,0.447661,...,57657.0,20839.0,9624.0,9573.0,555245.0,188998.0,0.483100,0.788167,0.050651,0.101573
6,Finland,7372,5802,European,Scandinavian,Cafe,2125,1204,1179,0.366253,...,42350.0,17078.0,6231.0,4338.0,247937.0,119323.0,0.413382,0.768301,0.036355,0.088575
7,France,155288,132871,French,European,Italian,84643,31729,16140,0.637031,...,804833.0,275266.0,155366.0,198309.0,15628055.0,2822427.0,0.492007,0.777163,0.070262,0.125309
8,Germany,115333,87491,German,European,Italian,32567,20365,15251,0.372233,...,335441.0,116732.0,51806.0,65186.0,4039822.0,1105082.0,0.484957,0.788501,0.058987,0.105867
9,Greece,33763,30138,Greek,Mediterranean,Seafood,22191,13886,5541,0.736313,...,322876.0,109208.0,52172.0,59093.0,3704203.0,1709704.0,0.682197,0.871046,0.034563,0.065079
10,Hungary,7431,6282,European,Hungarian,Central European,3732,3288,1109,0.594078,...,74883.0,27408.0,14650.0,18327.0,692990.0,329309.0,0.589237,0.816631,0.055653,0.100140
11,Ireland,11203,9788,Irish,European,Cafe,4580,2863,2446,0.467920,...,277847.0,96145.0,52771.0,58665.0,1331565.0,1202802.0,0.596419,0.827419,0.048774,0.092647
12,Italy,224763,195924,Italian,Mediterranean,Pizza,160924,58650,55432,0.821359,...,1364375.0,514952.0,266360.0,366587.0,29688209.0,5325444.0,0.528251,0.784450,0.068837,0.118853
13,Poland,24698,19033,European,Polish,Italian,10094,8865,3254,0.530342,...,91072.0,32573.0,15512.0,18702.0,1222023.0,367755.0,0.570750,0.818393,0.050855,0.093035
14,Portugal,32592,28680,European,Portuguese,Mediterranean,21440,21352,6867,0.747559,...,273124.0,91191.0,43884.0,53189.0,3442759.0,1163150.0,0.603329,0.838143,0.045728,0.083457
15,Romania,7842,6865,European,Romanian,Italian,3766,2748,1484,0.548580,...,50822.0,22661.0,12343.0,16969.0,312693.0,238385.0,0.568786,0.781979,0.071183,0.122961
16,Slovakia,4251,3147,European,Central European,Cafe,1368,630,599,0.434700,...,14691.0,5498.0,2690.0,3499.0,127940.0,56469.0,0.532876,0.793037,0.061963,0.109600
17,Spain,157479,134965,Spanish,Mediterranean,European,85973,54333,23803,0.637002,...,981613.0,357130.0,182048.0,273842.0,14667345.0,4198363.0,0.572540,0.806348,0.065226,0.108588
18,Sweden,18555,13384,European,Swedish,Cafe,5319,4400,2038,0.397415,...,70524.0,27060.0,11504.0,11329.0,738843.0,212854.0,0.434274,0.765600,0.053224,0.107271
19,The Netherlands,29792,25588,European,Dutch,Seafood,15332,12410,4759,0.599187,...,183234.0,59830.0,26090.0,29142.0,1824104.0,609989.0,0.510981,0.811370,0.047775,0.090546
20,United Kingdom,171664,147174,British,Cafe,Bar,64264,34735,28771,0.436653,...,4966746.0,2126588.0,1344001.0,1628584.0,23223345.0,22599356.0,0.554593,0.774366,0.072063,0.131534

In [37]:
score_parameters = ['open_days_per_week', 'open_hours_per_week', 'working_shifts_per_week', 'avg_rating', 'food', 'service', 'value', 'atmosphere']
df_average_by_country = df_upd_short[['country'] + score_parameters].groupby(['country']).mean(score_parameters).reset_index()
# df_average_by_country
df_base = df_base.join(df_average_by_country.set_index('country'), on='country')
df_base

,country,restaurant_cnt,cuisines_cnt,cuisine_no_1,cuisine_no_2,cuisine_no_3,cuisine_no_1_cnt,cuisine_no_2_cnt,cuisine_no_3_cnt,cuisine_no_1_prt,...,terrible_flg,terrible_and_poor_flg,open_days_per_week,open_hours_per_week,working_shifts_per_week,avg_rating,food,service,value,atmosphere
0,Austria,20487,16760,European,Austrian,Central European,10582,9404,2743,0.631384,...,0.054171,0.097982,6.091258,66.483475,6.824218,4.144475,4.187921,4.142813,4.041227,4.054033
1,Belgium,23711,20507,European,Belgian,French,11912,9992,4634,0.580875,...,0.064140,0.116937,5.713677,48.451676,7.411760,3.995374,4.056041,4.021697,3.933120,3.833555
2,Bulgaria,4469,3851,European,Eastern European,Mediterranean,1589,980,664,0.412620,...,0.062748,0.106251,6.728755,85.403788,6.793478,4.195942,4.242509,4.178044,4.150434,4.245614
3,Croatia,8375,7608,European,Croatian,Mediterranean,5348,5287,3529,0.702944,...,0.050392,0.091060,6.724611,87.747858,6.898187,4.141050,4.198630,4.203866,4.104639,4.123827
4,Czech Republic,14844,11319,European,Czech,Cafe,6271,5394,1939,0.554024,...,0.064846,0.108103,6.523331,73.602625,6.630181,4.040272,4.151011,4.061817,4.043077,4.067283
5,Denmark,9485,7117,European,Danish,Cafe,3186,2774,1288,0.447661,...,0.050651,0.101573,6.358717,59.542174,6.596116,3.930402,4.026227,4.000312,3.895803,3.923467
6,Finland,7372,5802,European,Scandinavian,Cafe,2125,1204,1179,0.366253,...,0.036355,0.088575,6.306100,62.407000,6.442921,3.936790,3.971234,4.002746,3.824761,3.917458
7,France,155288,132871,French,European,Italian,84643,31729,16140,0.637031,...,0.070262,0.125309,6.111181,51.533433,8.451443,4.018090,4.060964,4.076603,3.971429,3.838271
8,Germany,115333,87491,German,European,Italian,32567,20365,15251,0.372233,...,0.058987,0.105867,6.242100,60.576214,7.394672,4.057725,4.093484,4.037176,3.976119,3.991851
9,Greece,33763,30138,Greek,Mediterranean,Seafood,22191,13886,5541,0.736313,...,0.034563,0.065079,6.746998,90.713784,6.890273,4.325600,4.335215,4.381414,4.257506,4.341007
10,Hungary,7431,6282,European,Hungarian,Central European,3732,3288,1109,0.594078,...,0.055653,0.100140,6.471471,71.775381,6.538859,4.145468,4.196787,4.157687,4.112922,4.126130
11,Ireland,11203,9788,Irish,European,Cafe,4580,2863,2446,0.467920,...,0.048774,0.092647,6.453874,62.845239,6.652465,4.135357,4.246658,4.259562,4.107425,4.083561
12,Italy,224763,195924,Italian,Mediterranean,Pizza,160924,58650,55432,0.821359,...,0.068837,0.118853,6.289305,60.452992,8.503441,4.038021,4.098254,3.978757,3.935929,3.888864
13,Poland,24698,19033,European,Polish,Italian,10094,8865,3254,0.530342,...,0.050855,0.093035,6.728129,77.262177,6.773964,4.109489,4.166965,4.150178,4.076900,4.082375
14,Portugal,32592,28680,European,Portuguese,Mediterranean,21440,21352,6867,0.747559,...,0.045728,0.083457,6.287848,65.611509,7.887001,4.151862,4.202260,4.167637,4.065466,4.023893
15,Romania,7842,6865,European,Romanian,Italian,3766,2748,1484,0.548580,...,0.071183,0.122961,6.727341,84.935491,6.794821,4.099845,4.123928,4.029084,4.003604,4.056818
16,Slovakia,4251,3147,European,Central European,Cafe,1368,630,599,0.434700,...,0.061963,0.109600,6.504711,73.574966,6.608793,4.119490,4.187592,4.095798,4.077945,4.196697
17,Spain,157479,134965,Spanish,Mediterranean,European,85973,54333,23803,0.637002,...,0.065226,0.108588,6.297108,66.489934,7.851169,3.959886,4.053639,4.018247,3.935742,3.951327
18,Sweden,18555,13384,European,Swedish,Cafe,5319,4400,2038,0.397415,...,0.053224,0.107271,6.252466,58.243135,6.514663,3.860476,3.974258,3.928718,3.794992,3.918235
19,The Netherlands,29792,25588,European,Dutch,Seafood,15332,12410,4759,0.599187,...,0.047775,0.090546,6.233038,59.627108,6.330262,4.065244,4.086359,4.096163,3.962758,4.011135
20,United Kingdom,171664,147174,British,Cafe,Bar,64264,34735,28771,0.436653,...,0.072063,0.131534,6.510160,61.267496,7.003771,4.007406,4.129458,4.131486,4.022993,3.938211

In [38]:
df_upd_median = df_upd_short.groupby(['country'])[['price_min', 'price_max']].median().reset_index()
df_base = df_base.join(df_upd_median.set_index('country'), on='country')
df_base

,country,restaurant_cnt,cuisines_cnt,cuisine_no_1,cuisine_no_2,cuisine_no_3,cuisine_no_1_cnt,cuisine_no_2_cnt,cuisine_no_3_cnt,cuisine_no_1_prt,...,open_days_per_week,open_hours_per_week,working_shifts_per_week,avg_rating,food,service,value,atmosphere,price_min,price_max
0,Austria,20487,16760,European,Austrian,Central European,10582,9404,2743,0.631384,...,6.091258,66.483475,6.824218,4.144475,4.187921,4.142813,4.041227,4.054033,5.0,20.0
1,Belgium,23711,20507,European,Belgian,French,11912,9992,4634,0.580875,...,5.713677,48.451676,7.411760,3.995374,4.056041,4.021697,3.933120,3.833555,10.0,26.0
2,Bulgaria,4469,3851,European,Eastern European,Mediterranean,1589,980,664,0.412620,...,6.728755,85.403788,6.793478,4.195942,4.242509,4.178044,4.150434,4.245614,3.0,15.0
3,Croatia,8375,7608,European,Croatian,Mediterranean,5348,5287,3529,0.702944,...,6.724611,87.747858,6.898187,4.141050,4.198630,4.203866,4.104639,4.123827,5.0,25.0
4,Czech Republic,14844,11319,European,Czech,Cafe,6271,5394,1939,0.554024,...,6.523331,73.602625,6.630181,4.040272,4.151011,4.061817,4.043077,4.067283,3.0,12.0
5,Denmark,9485,7117,European,Danish,Cafe,3186,2774,1288,0.447661,...,6.358717,59.542174,6.596116,3.930402,4.026227,4.000312,3.895803,3.923467,8.0,27.0
6,Finland,7372,5802,European,Scandinavian,Cafe,2125,1204,1179,0.366253,...,6.306100,62.407000,6.442921,3.936790,3.971234,4.002746,3.824761,3.917458,7.0,20.0
7,France,155288,132871,French,European,Italian,84643,31729,16140,0.637031,...,6.111181,51.533433,8.451443,4.018090,4.060964,4.076603,3.971429,3.838271,10.0,24.0
8,Germany,115333,87491,German,European,Italian,32567,20365,15251,0.372233,...,6.242100,60.576214,7.394672,4.057725,4.093484,4.037176,3.976119,3.991851,5.0,20.0
9,Greece,33763,30138,Greek,Mediterranean,Seafood,22191,13886,5541,0.736313,...,6.746998,90.713784,6.890273,4.325600,4.335215,4.381414,4.257506,4.341007,5.0,16.0
10,Hungary,7431,6282,European,Hungarian,Central European,3732,3288,1109,0.594078,...,6.471471,71.775381,6.538859,4.145468,4.196787,4.157687,4.112922,4.126130,3.0,12.0
11,Ireland,11203,9788,Irish,European,Cafe,4580,2863,2446,0.467920,...,6.453874,62.845239,6.652465,4.135357,4.246658,4.259562,4.107425,4.083561,5.0,20.0
12,Italy,224763,195924,Italian,Mediterranean,Pizza,160924,58650,55432,0.821359,...,6.289305,60.452992,8.503441,4.038021,4.098254,3.978757,3.935929,3.888864,10.0,30.0
13,Poland,24698,19033,European,Polish,Italian,10094,8865,3254,0.530342,...,6.728129,77.262177,6.773964,4.109489,4.166965,4.150178,4.076900,4.082375,2.0,9.0
14,Portugal,32592,28680,European,Portuguese,Mediterranean,21440,21352,6867,0.747559,...,6.287848,65.611509,7.887001,4.151862,4.202260,4.167637,4.065466,4.023893,7.0,20.0
15,Romania,7842,6865,European,Romanian,Italian,3766,2748,1484,0.548580,...,6.727341,84.935491,6.794821,4.099845,4.123928,4.029084,4.003604,4.056818,3.0,14.0
16,Slovakia,4251,3147,European,Central European,Cafe,1368,630,599,0.434700,...,6.504711,73.574966,6.608793,4.119490,4.187592,4.095798,4.077945,4.196697,3.0,14.0
17,Spain,157479,134965,Spanish,Mediterranean,European,85973,54333,23803,0.637002,...,6.297108,66.489934,7.851169,3.959886,4.053639,4.018247,3.935742,3.951327,8.0,22.0
18,Sweden,18555,13384,European,Swedish,Cafe,5319,4400,2038,0.397415,...,6.252466,58.243135,6.514663,3.860476,3.974258,3.928718,3.794992,3.918235,8.0,22.0
19,The Netherlands,29792,25588,European,Dutch,Seafood,15332,12410,4759,0.599187,...,6.233038,59.627108,6.330262,4.065244,4.086359,4.096163,3.962758,4.011135,7.0,22.0
20,United Kingdom,171664,147174,British,Cafe,Bar,64264,34735,28771,0.436653,...,6.510160,61.267496,7.003771,4.007406,4.129458,4.131486,4.022993,3.938211,6.0,20.0

In [39]:
import numpy as np

# получаю список названий колонок о расписании
df_schedule_sample = df_schedule[5:6]
df_schedule_sample_list = df_schedule_sample['original_open_hours'].apply(lambda x: new_schedule_parameters(dict_by_cell(x)).keys())
schedule_parameters = list(df_schedule_sample_list.reset_index()['original_open_hours'].tolist()[0])
schedule_parameters.remove('break_flg')

# print(list(df_upd_short))
df_upd_short['break_flg'].replace({False: 0, True: 1}, inplace=True)
df_means = df_upd_short[['country', 'break_flg']].groupby('country').mean(['break_flg']).reset_index()
# print(list(df_means))

for name in schedule_parameters:
#     print(name)
    name_avg = name+'_avg'
    df_schedule4[name_avg] = df_schedule4[name].values.astype(np.int64)
    kek = df_schedule4[['country', name_avg]].groupby('country').mean(name_avg).reset_index()
    df_means = df_means.join(kek.set_index('country'), on='country')
#     print(list(df_means))
    if name in ['min_open_dttm', 'max_close_dttm']:
        df_means[name_avg] = pd.to_datetime(df_means[name_avg].apply(lambda x: round(x, 0)))
    elif name in ['min_open_sec', 'max_close_sec']:
        df_means[name_avg] = df_means[name_avg].apply(lambda x: round(x, 0))
    else:
        df_means[name_avg] = pd.to_timedelta(df_means[name_avg].apply(lambda x: round(x, 0)))

# df_upd = pd.merge(df_upd, df_schedule4,  how='left', left_on=['restaurant_link','country'], right_on = ['restaurant_link','country'])

        
# df_means.sort_values(by=['break_flg'])
df_means.sort_values(by=['max_break_hours_avg'])
df_means

,country,break_flg,min_open_dttm_avg,min_open_sec_avg,max_close_dttm_avg,max_close_sec_avg,max_break_hours_avg,max_no_weekend_hours_avg,max_weekend_hours_avg,open_mon_hours_avg,open_tue_hours_avg,open_wed_hours_avg,open_thu_hours_avg,open_fri_hours_avg,open_sat_hours_avg,open_sun_hours_avg
0,Austria,0.151233,2022-01-01 10:11:11.255438080,1.641017e+09,2022-01-01 21:59:47.414543360,1.641060e+09,0 days 00:29:41.044126787,0 days 10:56:38.713486638,0 days 10:19:52.952144189,0 days 08:11:56.929770044,0 days 09:04:17.054070851,0 days 09:47:27.576134245,0 days 10:21:44.207582349,0 days 10:45:20.540708515,0 days 10:02:20.441267868,0 days 07:57:18.222498446
1,Belgium,0.391138,2022-01-01 11:08:07.066041856,1.641021e+09,2022-01-01 21:45:05.966766080,1.641059e+09,0 days 01:29:12.516403920,0 days 08:42:19.510864934,0 days 08:15:06.503621645,0 days 05:16:24.010225820,0 days 06:01:04.279505752,0 days 06:44:51.527907968,0 days 07:37:33.857690669,0 days 08:26:38.111631870,0 days 07:49:32.569237324,0 days 06:22:23.381337878
2,Bulgaria,0.013340,2022-01-01 09:20:04.980237312,1.641014e+09,2022-01-01 22:18:15.296442624,1.641061e+09,0 days 00:02:26.294466403,0 days 12:44:42.717391304,0 days 12:18:10.405138340,0 days 12:11:57.391304348,0 days 12:29:02.341897233,0 days 12:30:01.926877470,0 days 12:30:46.808300395,0 days 12:36:30.029644269,0 days 12:12:29.347826087,0 days 10:52:46.660079051
3,Croatia,0.029275,2022-01-01 09:24:48.668393728,1.641015e+09,2022-01-01 22:49:26.735751424,1.641063e+09,0 days 00:07:01.088082902,0 days 13:04:10.010362694,0 days 12:54:55.352331606,0 days 12:19:35.409326425,0 days 12:38:27.575129534,0 days 12:42:02.549222798,0 days 12:46:30.419689119,0 days 12:51:13.632124352,0 days 12:43:26.860103627,0 days 11:30:39.886010363
4,Czech Republic,0.023455,2022-01-01 10:10:26.768429056,1.641017e+09,2022-01-01 22:05:08.436336640,1.641060e+09,0 days 00:04:10.186150410,0 days 11:35:18.064035741,0 days 10:22:03.596425912,0 days 10:23:46.008935220,0 days 10:54:07.334326136,0 days 11:03:41.630677587,0 days 11:06:09.620253165,0 days 11:27:34.013402829,0 days 10:13:10.752047655,0 days 08:22:16.187639613
5,Denmark,0.053677,2022-01-01 11:22:39.341042944,1.641022e+09,2022-01-01 21:40:08.431158528,1.641059e+09,0 days 00:09:02.592188523,0 days 09:42:00.785511674,0 days 09:24:48.308967925,0 days 07:27:59.423958106,0 days 08:21:18.603534803,0 days 08:42:33.122408902,0 days 09:00:58.298058041,0 days 09:28:13.288239145,0 days 09:14:35.845516038,0 days 07:02:28.003491163
6,Finland,0.033296,2022-01-01 10:09:53.788472320,1.641017e+09,2022-01-01 21:10:09.535534336,1.641057e+09,0 days 00:07:11.617235590,0 days 10:23:16.754336877,0 days 09:16:51.925013990,0 days 08:29:44.118634583,0 days 09:10:44.655847790,0 days 09:32:07.923894796,0 days 09:35:04.448796866,0 days 10:15:33.172915501,0 days 09:06:04.801343033,0 days 06:02:54.795747062
7,France,0.474768,2022-01-01 10:37:08.435503104,1.641019e+09,2022-01-01 21:36:17.873744640,1.641059e+09,0 days 02:06:50.326522014,0 days 08:43:27.355522786,0 days 08:03:36.566252370,0 days 06:09:46.317674321,0 days 07:32:16.290990801,0 days 07:43:30.169229689,0 days 08:10:34.853591742,0 days 08:31:12.320763991,0 days 07:54:47.363949161,0 days 05:19:36.317674321
8,Germany,0.248170,2022-01-01 11:03:30.005202944,1.641021e+09,2022-01-01 22:08:42.410419968,1.641061e+09,0 days 00:45:22.985188525,0 days 09:42:38.757848,0 days 09:44:49.184848590,0 days 07:10:44.604044538,0 days 08:18:50.934128829,0 days 08:53:43.549897672,0 days 09:12:29.671164452,0 days 09:32:19.439800201,0 days 09:14:20.702070831,0 days 08:02:54.119463041
9,Greece,0.026876,2022-01-01 09:18:09.168307968,1.641014e+09,2022-01-01 23:16:04.056166144,1.641065e+09,0 days 00:07:01.227523985,0 days 13:23:26.586187178,0 days 13:25:57.239977127,0 days 12:26:12.473473537,0 days 12:52:31.545841540,0 days 12:58:25.816125548,0 days 13:02:26.197344177,0 days 13:10:39.536184002,0 days 13:14:16.971853358,0 days 12:30:06.648452888
10,Hungary,0.015494,2022-01-01 10:08:03.792424960,1.641017e+09,2022-01-01 21:41:38.780128000,1.641059e+09,0 days 00:03:04.604033448,0 days 11:16:30.383669454,0 days 10:37:34.058042302,0 days 09:44:03.438268569,0 days 10:22:42.734874570,0 days 10:36:32.346286276,0 days 10:49:14.889326119,0 days 11:08:56.635514019,0 days 10:30:10.698475160,0 days 08:30:10.846040334
11,Ireland,0.054802,2022-01-01 10:45:08.833533952,1.641020e+09,2022-01-01 21:30:50.084178176,1.641058e+09,0 days 00:10:22.624978526,0 days 09:58:37.673939186,0 days 09:57:16.213708985,0 days 08:12:45.219034530,0 days 08:34:35.736127813,0 days 09:01:16.110633912,0 days 09:22:28.242570005,0 days 09:45:19.738876482,0 days 09:35:05.339288782,0 days 08:11:02.040886446
12,Italy,0.425287,2022-01-01 10:53:41.586931200,1.641020e+09,2022-01-01 22:41:37.781949184,1.641062e+09,0 days 01:40:55.657247222,0 days 09:39:41.271371316,0 days 09:39:20.538785450,0 days 07:04:59.672264218,0 days 08:15:08.497285780,0 days 08:42:38.744863274,0 days 09:07:33.259601238,0 days 09:29:54.030236924,0 days 09:25:33.369692050,0 days 08:03:10.938562224
13,Poland,0.009496,2022-01-01 09:50:52.628981760,1.641016e+09,2022-01-01 21:58:15.580977920,1.641060e+09,0 days 00:02:17.411395245,0 days 11:47:11.139524450,0 days 11:28:20.919694930,0 days 10:26:15.737999103,0 days 11:05:04.239569314,0 days 11:10:34.176760879,0 days 11:14:30.632570659,0 days 11:38:22.503364738,0 days 11:21:02.440556303,0 days 10:12:22.418124720
14,Portugal,0.295667,2022-01-01 10:38:35.028514304,1.641019e+09,2022-01-01 22:34:38.414956800,1.641062e+09,0 days 01:08:23.556940443,0 days 10:36:11.866658828,0 days 10:12:15.517667117,0 days 08:07:32.777941090,0 days 09:22:03.513434064,0 days 09:47:29.123405256,0 days 10:07:04.169557293,0 days 10:26:25.285437122,0 days 10:00:35.779881239,0 days 07:29:04.585807514
15,Romania,0.014442,2022-01-01 09:08:42.370518016,1.641014e+09,2022-01-01 22:22:35.483067904,1.641061e+09,0 days 00:03:24.158366534,0 days 12:50:07.380478088,0 days 12:09:22.739043825,0 days 12:01:30.881474104,0 days 12:23:06.678286853,0 days 12:25:35.229083665,0 days 12:29:55.607569721,0 days 12:32:26.743027888,0 days 11:53:12.878486056,0 days 10:57:50.348605578
16,Slovakia,0.028264,2022-01-01 09:31:09.313593600,1.641015e+09,2022-01-01 21:44:07.294750976,1.641059e+09,0 days 00:07:00.726783311,0 days 11:50:13.216689098,0 days 10:07:44.710632571,0 days 10:37:57.092866756,0 days 11:01:23.849259758,0 days 11:06:01.668909825,0 days 11:07:04.629878869,0 days 11:37:31.386271871,0 days 09:59:24.037685061,0 days 07:50:02.368775236
17,Spain,0.314697,2022-01-01 10:30:35.714776064,1.641019e+09,2022-01-01 22:47:09.440908544,1.641063e+09,0 days 01:10:07.109203750,0 days 10:49:33.188168493,0 days 10:31:09.086755579,0 days 07:58:56.631189753,0 days 09:06:38.377657467,0 days 09:36:02.697741978,0 days 10:04:11.641885646,0 days 10:38:07.494255909,0 days 10:21:37.393635283,0 days 08:25:41.734583388
18,Sweden,0.065316,2022-01-01 10:36:03.255132160,1.641019e+09,2022-01-01 21:09:16.947480576,1.641057e+09,0 days 00:12:51.170354572,0 days 09:40:33.031191682,0 days 08:46:57.352705945,0 days 07:36:13.372434018,0 days 08:22:43.684350840,0 days 08:43:22.122100773,0 days 08:51:15.659824047,0 days 09:27:24.153559051,0 days 08:38:37.118101840,0 days 06:16:24.193548387
19,The Netherlands,0.024567,2022-01-01 11:38:28.479054336,1.641023e+09,2022-01-01 21:56:17.914131712,1.641060e+09,0 days 00:04:59.829654094,0 days 09:49:56.613940553,0 days 09:39:49.184773162,0 days 06:29:00.055623153,0 days 07:45:23.928385190,0 days 08:47:55.612723796,0 days 09:13:24.825308535,0 days 09:40:30.822179732,0 days 09:29:32.299669738,0 days 08:03:18.953589432
20,United Kingdom,0.108121,2022-01-01 10:57:16.367395584,1.641020e+09,2022-01-01 21:17:06.798120960,1.641057e+09,0 days 00:19:38.617433395,0 days 09:39:39.733024899,0 days 09:34:20.593524467,0 days 07:59:10.169612371,0 days 08:30:35.994581277,0 days 08:55:12.575240238,0 days 09:06:52.480808689,0 days 09:29:12.915574076,0 days 09:23:38.662114094,0 days 07:43:47.875369368

In [40]:
df_base = df_base.join(df_means.set_index('country'), on='country')
df_base

,country,restaurant_cnt,cuisines_cnt,cuisine_no_1,cuisine_no_2,cuisine_no_3,cuisine_no_1_cnt,cuisine_no_2_cnt,cuisine_no_3_cnt,cuisine_no_1_prt,...,max_break_hours_avg,max_no_weekend_hours_avg,max_weekend_hours_avg,open_mon_hours_avg,open_tue_hours_avg,open_wed_hours_avg,open_thu_hours_avg,open_fri_hours_avg,open_sat_hours_avg,open_sun_hours_avg
0,Austria,20487,16760,European,Austrian,Central European,10582,9404,2743,0.631384,...,0 days 00:29:41.044126787,0 days 10:56:38.713486638,0 days 10:19:52.952144189,0 days 08:11:56.929770044,0 days 09:04:17.054070851,0 days 09:47:27.576134245,0 days 10:21:44.207582349,0 days 10:45:20.540708515,0 days 10:02:20.441267868,0 days 07:57:18.222498446
1,Belgium,23711,20507,European,Belgian,French,11912,9992,4634,0.580875,...,0 days 01:29:12.516403920,0 days 08:42:19.510864934,0 days 08:15:06.503621645,0 days 05:16:24.010225820,0 days 06:01:04.279505752,0 days 06:44:51.527907968,0 days 07:37:33.857690669,0 days 08:26:38.111631870,0 days 07:49:32.569237324,0 days 06:22:23.381337878
2,Bulgaria,4469,3851,European,Eastern European,Mediterranean,1589,980,664,0.412620,...,0 days 00:02:26.294466403,0 days 12:44:42.717391304,0 days 12:18:10.405138340,0 days 12:11:57.391304348,0 days 12:29:02.341897233,0 days 12:30:01.926877470,0 days 12:30:46.808300395,0 days 12:36:30.029644269,0 days 12:12:29.347826087,0 days 10:52:46.660079051
3,Croatia,8375,7608,European,Croatian,Mediterranean,5348,5287,3529,0.702944,...,0 days 00:07:01.088082902,0 days 13:04:10.010362694,0 days 12:54:55.352331606,0 days 12:19:35.409326425,0 days 12:38:27.575129534,0 days 12:42:02.549222798,0 days 12:46:30.419689119,0 days 12:51:13.632124352,0 days 12:43:26.860103627,0 days 11:30:39.886010363
4,Czech Republic,14844,11319,European,Czech,Cafe,6271,5394,1939,0.554024,...,0 days 00:04:10.186150410,0 days 11:35:18.064035741,0 days 10:22:03.596425912,0 days 10:23:46.008935220,0 days 10:54:07.334326136,0 days 11:03:41.630677587,0 days 11:06:09.620253165,0 days 11:27:34.013402829,0 days 10:13:10.752047655,0 days 08:22:16.187639613
5,Denmark,9485,7117,European,Danish,Cafe,3186,2774,1288,0.447661,...,0 days 00:09:02.592188523,0 days 09:42:00.785511674,0 days 09:24:48.308967925,0 days 07:27:59.423958106,0 days 08:21:18.603534803,0 days 08:42:33.122408902,0 days 09:00:58.298058041,0 days 09:28:13.288239145,0 days 09:14:35.845516038,0 days 07:02:28.003491163
6,Finland,7372,5802,European,Scandinavian,Cafe,2125,1204,1179,0.366253,...,0 days 00:07:11.617235590,0 days 10:23:16.754336877,0 days 09:16:51.925013990,0 days 08:29:44.118634583,0 days 09:10:44.655847790,0 days 09:32:07.923894796,0 days 09:35:04.448796866,0 days 10:15:33.172915501,0 days 09:06:04.801343033,0 days 06:02:54.795747062
7,France,155288,132871,French,European,Italian,84643,31729,16140,0.637031,...,0 days 02:06:50.326522014,0 days 08:43:27.355522786,0 days 08:03:36.566252370,0 days 06:09:46.317674321,0 days 07:32:16.290990801,0 days 07:43:30.169229689,0 days 08:10:34.853591742,0 days 08:31:12.320763991,0 days 07:54:47.363949161,0 days 05:19:36.317674321
8,Germany,115333,87491,German,European,Italian,32567,20365,15251,0.372233,...,0 days 00:45:22.985188525,0 days 09:42:38.757848,0 days 09:44:49.184848590,0 days 07:10:44.604044538,0 days 08:18:50.934128829,0 days 08:53:43.549897672,0 days 09:12:29.671164452,0 days 09:32:19.439800201,0 days 09:14:20.702070831,0 days 08:02:54.119463041
9,Greece,33763,30138,Greek,Mediterranean,Seafood,22191,13886,5541,0.736313,...,0 days 00:07:01.227523985,0 days 13:23:26.586187178,0 days 13:25:57.239977127,0 days 12:26:12.473473537,0 days 12:52:31.545841540,0 days 12:58:25.816125548,0 days 13:02:26.197344177,0 days 13:10:39.536184002,0 days 13:14:16.971853358,0 days 12:30:06.648452888
10,Hungary,7431,6282,European,Hungarian,Central European,3732,3288,1109,0.594078,...,0 days 00:03:04.604033448,0 days 11:16:30.383669454,0 days 10:37:34.058042302,0 days 09:44:03.438268569,0 days 10:22:42.734874570,0 days 10:36:32.346286276,0 days 10:49:14.889326119,0 days 11:08:56.635514019,0 days 10:30:10.698475160,0 days 08:30:10.846040334
11,Ireland,11203,9788,Irish,European,Cafe,4580,2863,2446,0.467920,...,0 days 00:10:22.624978526,0 days 09:58:37.673939186,0 days 09:57:16.213708985,0 days 08:12:45.219034530,0 days 08:34:35.736127813,0 days 09:01:16.110633912,0 days 09:22:28.242570005,0 days 09:45:19.738876482,0 days 09:35:05.339288782,0 days 08:11:02.040886446
12,Italy,224763,195924,Italian,Mediterranean,Pizza,160924,58650,55432,0.821359,...,0 days 01:40:55.657247222,0 days 09:39:41.271371316,0 days 09:39:20.538785450,0 days 07:04:59.672264218,0 days 08:15:08.497285780,0 days 08:42:38.744863274,0 days 09:07:33.259601238,0 days 09:29:54.030236924,0 days 09:25:33.369692050,0 days 08:03:10.938562224
13,Poland,24698,19033,European,Polish,Italian,10094,8865,3254,0.530342,...,0 days 00:02:17.411395245,0 days 11:47:11.139524450,0 days 11:28:20.919694930,0 days 10:26:15.737999103,0 days 11:05:04.239569314,0 days 11:10:34.176760879,0 days 11:14:30.632570659,0 days 11:38:22.503364738,0 days 11:21:02.440556303,0 days 10:12:22.418124720
14,Portugal,32592,28680,European,Portuguese,Mediterranean,21440,21352,6867,0.747559,...,0 days 01:08:23.556940443,0 days 10:36:11.866658828,0 days 10:12:15.517667117,0 days 08:07:32.777941090,0 days 09:22:03.513434064,0 days 09:47:29.123405256,0 days 10:07:04.169557293,0 days 10:26:25.285437122,0 days 10:00:35.779881239,0 days 07:29:04.585807514
15,Romania,7842,6865,European,Romanian,Italian,3766,2748,1484,0.548580,...,0 days 00:03:24.158366534,0 days 12:50:07.380478088,0 days 12:09:22.739043825,0 days 12:01:30.881474104,0 days 12:23:06.678286853,0 days 12:25:35.229083665,0 days 12:29:55.607569721,0 days 12:32:26.743027888,0 days 11:53:12.878486056,0 days 10:57:50.348605578
16,Slovakia,4251,3147,European,Central European,Cafe,1368,630,599,0.434700,...,0 days 00:07:00.726783311,0 days 11:50:13.216689098,0 days 10:07:44.710632571,0 days 10:37:57.092866756,0 days 11:01:23.849259758,0 days 11:06:01.668909825,0 days 11:07:04.629878869,0 days 11:37:31.386271871,0 days 09:59:24.037685061,0 days 07:50:02.368775236
17,Spain,157479,134965,Spanish,Mediterranean,European,85973,54333,23803,0.637002,...,0 days 01:10:07.109203750,0 days 10:49:33.188168493,0 days 10:31:09.086755579,0 days 07:58:56.631189753,0 days 09:06:38.377657467,0 days 09:36:02.697741978,0 days 10:04:11.641885646,0 days 10:38:07.494255909,0 days 10:21:37.393635283,0 days 08:25:41.734583388
18,Sweden,18555,13384,European,Swedish,Cafe,5319,4400,2038,0.397415,...,0 days 00:12:51.170354572,0 days 09:40:33.031191682,0 days 08:46:57.352705945,0 days 07:36:13.372434018,0 days 08:22:43.684350840,0 days 08:43:22.122100773,0 days 08:51:15.659824047,0 days 09:27:24.153559051,0 days 08:38:37.118101840,0 days 06:16:24.193548387
19,The Netherlands,29792,25588,European,Dutch,Seafood,15332,12410,4759,0.599187,...,0 days 00:04:59.829654094,0 days 09:49:56.613940553,0 days 09:39:49.184773162,0 days 06:29:00.055623153,0 days 07:45:23.928385190,0 days 08:47:55.612723796,0 days 09:13:24.825308535,0 days 09:40:30.822179732,0 days 09:29:32.299669738,0 days 08:03:18.953589432
20,United Kingdom,171664,147174,British,Cafe,Bar,64264,34735,28771,0.436653,...,0 days 00:19:38.617433395,0 days 09:39:39.733024899,0 days 09:34:20.593524467,0 days 07:59:10.169612371,0 days 08:30:35.994581277,0 days 08:55:12.575240238,0 days 09:06:52.480808689,0 days 09:29:12.915574076,0 days 09:23:38.662114094,0 days 07:43:47.875369368

In [41]:
# выгрузить датасет
df_base.to_csv('tripadvisor_european_restaurants_aggr_full_11.csv')

In [42]:
# выгрузить датасет - все кухни
# df_all_cuisines_ok2.to_csv('tripadvisor_european_restaurants_cuisines.csv')